  /* ============ 取引一覧 ============ */
  const KIND_TAG = { expense: ['exp', '支出'], income: ['inc', '収入'], transfer: ['mv', '振替'], card_payment: ['mv', 'カード引落'], prepaid_amount: ['mv', '前払(金)'], prepaid_goods: ['mv', '前払(物)'], goods_use: ['exp', '現物利用'], generic: ['mv', '—'] };
  function txPositiveAmount(t) { return t.lines.filter(l => l.amount > 0).reduce((sum, l) => sum + l.amount, 0); }
  function filteredRows() { const ym = $('#fltYm').value, catTop = $('#fltCat').value, kind = $('#fltKind').value, kw = ($('#fltText').value || '').trim(), sort = ($('#fltSort') ? $('#fltSort').value : 'date_desc'); let rows = state.transactions.slice(); if (ym) rows = rows.filter(t => t.date.startsWith(ym)); if (catTop) rows = rows.filter(t => t.lines.some(l => l.ref.startsWith('cat:') && l.ref.includes('>' + catTop))); if (kind) rows = rows.filter(t => t.kind === kind); if (kw) rows = rows.filter(t => { const catText = t.lines.filter(l => l.ref.startsWith('cat:')).map(l => l.ref.slice(4)).join(' '); return (t.store + ' ' + t.branch + ' ' + t.memo + ' ' + catText).includes(kw); }); const cmpDateAsc = (a,b)=>a.date.localeCompare(b.date)||a.id.localeCompare(b.id); const cmpAmtAsc = (a,b)=>txPositiveAmount(a)-txPositiveAmount(b)||cmpDateAsc(a,b); rows.sort((a,b)=> sort==='date_asc'?cmpDateAsc(a,b):sort==='amount_desc'?cmpAmtAsc(b,a):sort==='amount_asc'?cmpAmtAsc(a,b):cmpDateAsc(b,a)); return rows; }
  function renderList() {
    if (!$('#fltKind').dataset.filled) { $('#fltKind').innerHTML = `<option value="">すべて</option>` + Object.entries(KIND_TAG).filter(([k]) => k !== 'generic').map(([k, v]) => `<option value="${k}">${v[1]}</option>`).join(''); $('#fltKind').dataset.filled = '1'; }
    if (!$('#fltCat').dataset.filled) { const tops = [...new Set(Object.keys(state.categories.expense).concat(Object.keys(state.categories.income)))]; $('#fltCat').innerHTML = `<option value="">すべて</option>` + tops.map(t => `<option>${t}</option>`).join(''); $('#fltCat').dataset.filled = '1'; }
    const rows = filteredRows(); const rowIds = new Set(rows.map(r => r.id)); selected.forEach(id => { if (!rowIds.has(id)) selected.delete(id); });
    const tbody = $('#txTable tbody');
    tbody.innerHTML = rows.map(t => { const debit = t.lines.filter(l => l.amount > 0).map(l => refLabel(l.ref)).join(', '); const credit = t.lines.filter(l => l.amount < 0).map(l => refLabel(l.ref) + (l.qty ? `(${-l.qty}枚)` : '')).join(' + '); const amt = t.lines.filter(l => l.amount > 0).reduce((s, l) => s + l.amount, 0); const [cls, lab] = KIND_TAG[t.kind] || KIND_TAG.generic; return `<tr class="${selected.has(t.id) ? 'sel' : ''}" data-id="${t.id}"><td class="chk"><input type="checkbox" class="rowchk" ${selected.has(t.id) ? 'checked' : ''}></td><td>${t.date}</td><td><span class="tag ${cls}">${lab}</span></td><td>${esc(debit)}</td><td class="muted">${esc(credit)}</td><td>${esc(t.store)}${t.branch ? ' <span class="muted">/ ' + esc(t.branch) + '</span>' : ''}</td><td class="num">${yen(amt)}</td><td style="white-space:nowrap"><button class="btn ghost sm" data-edit="${t.id}">編集</button> <button class="btn danger sm" data-del="${t.id}">削除</button></td></tr>`; }).join('') || `<tr><td colspan="8" class="muted" style="text-align:center; padding:20px">取引がありません</td></tr>`;
    $$('.rowchk', tbody).forEach(chk => chk.addEventListener('change', e => { const id = e.target.closest('tr').dataset.id; if (e.target.checked) selected.add(id); else selected.delete(id); e.target.closest('tr').classList.toggle('sel', e.target.checked); renderBulkBar(); syncChkAll(rows); }));
    $$('[data-del]', tbody).forEach(b => b.addEventListener('click', () => { if (!confirm('この取引を削除しますか？')) return; state.transactions = state.transactions.filter(t => t.id !== b.dataset.del); selected.delete(b.dataset.del); persist(); renderList(); renderAccounts(); renderReport(); renderCards(); renderDrill(); renderBudget(); toast('削除しました'); }));
    $$('[data-edit]', tbody).forEach(b => b.addEventListener('click', () => loadForEdit(b.dataset.edit)));
    syncChkAll(rows); renderBulkBar();
  }
  function gotoListWithKeyword(kw) { switchTab('list'); $('#fltYm').value = ''; $('#fltCat').value = ''; $('#fltKind').value = ''; $('#fltText').value = kw; renderList(); toast(`「${kw}」で取引を検索`); }
  function syncChkAll(rows) { const all = $('#chkAll'); if (!all) return; const n = rows.length; const sel = rows.filter(r => selected.has(r.id)).length; all.checked = n > 0 && sel === n; all.indeterminate = sel > 0 && sel < n; }
  function renderBulkBar() { const bar = $('#bulkBar'); if (!bar) return; if (!selected.size) { bar.innerHTML = ''; return; } bar.innerHTML = `<div class="bulkbar"><span class="cnt">${selected.size}件を選択中</span><span class="spacer"></span><button class="btn ghost sm" id="bulkRecat">カテゴリを付け替え</button><button class="btn danger sm" id="bulkDel">一括削除</button><button class="btn ghost sm" id="bulkClear">選択解除</button></div>`; $('#bulkClear').addEventListener('click', () => { selected.clear(); renderList(); }); $('#bulkDel').addEventListener('click', () => { if (!confirm(`選択した ${selected.size}件を削除します。よろしいですか？`)) return; state.transactions = state.transactions.filter(t => !selected.has(t.id)); selected.clear(); persist(); renderList(); renderAccounts(); renderReport(); renderCards(); renderDrill(); renderBudget(); toast('一括削除しました ✓'); }); $('#bulkRecat').addEventListener('click', openBulkRecatModal); }
  function openBulkRecatModal() {
    const ids = [...selected]; const targets = state.transactions.filter(t => ids.includes(t.id)); const fromSet = new Map();
    targets.forEach(t => t.lines.forEach(l => { if (l.ref.startsWith('cat:exp>')) { const p = l.ref.slice(4); fromSet.set(p, (fromSet.get(p) || 0) + 1); } }));
    if (!fromSet.size) return toast('費用カテゴリを持つ取引が選択されていません');
    const fromOpts = [...fromSet.entries()].sort((a, b) => b[1] - a[1]).map(([p, n]) => `<option value="${p}">${p.replace(/^exp>/, '').split('>').join(' › ')}（${n}件）</option>`).join('');
    $('#modal').innerHTML = `<h3>カテゴリの一括付け替え（選択カテゴリのみ）</h3><p class="hint">選択した取引の中で、<b>付け替え元</b>に一致する費用明細だけを<b>付け替え先</b>に変更します。分割明細の他カテゴリはそのまま保持されます。</p><div class="field"><label>付け替え元カテゴリ</label><select id="brc_from">${fromOpts}</select></div><div class="field"><label>付け替え先カテゴリ</label><select id="brc_to" class="catsel">${categoryOptions('expense')}</select></div><div class="actions"><button class="btn ghost" id="brc_cancel">キャンセル</button><button class="btn" id="brc_ok">付け替える</button></div>`;
    $('#brc_cancel').addEventListener('click', closeModal);
    $('#brc_ok').addEventListener('click', () => { const fromRef = 'cat:' + $('#brc_from').value, toRef = 'cat:' + $('#brc_to').value; if (fromRef === toRef) { closeModal(); return toast('付け替え元と先が同じです'); } let cnt = 0; targets.forEach(t => { let changed = false; t.lines.forEach(l => { if (l.ref === fromRef) { l.ref = toRef; changed = true; } }); if (changed) { const merged = {}; const order = []; const others = []; t.lines.forEach(l => { if (l.ref.startsWith('cat:') && l.amount > 0) { if (!(l.ref in merged)) { merged[l.ref] = 0; order.push(l.ref); } merged[l.ref] += l.amount; } else others.push(l); }); t.lines = order.map(ref => ({ ref, amount: merged[ref] })).concat(others); cnt++; } }); persist(); closeModal(); renderList(); renderAccounts(); renderReport(); renderDrill(); renderBudget(); toast(`${cnt}件を付け替えました ✓`); });
    showModal();
  }

