  /* ============ 残高・口座 ============ */

  function accountFlowRows(accId) {
    const rows = [];
    state.transactions.forEach(t => t.lines.forEach(l => {
      if (l.ref === 'acc:' + accId) rows.push({ date: t.date, id: t.id, kind: t.kind, store: t.store, branch: t.branch, memo: t.memo, amount: l.amount, qty: l.qty });
    }));
    rows.sort((a, b) => a.date.localeCompare(b.date) || a.id.localeCompare(b.id));
    return rows;
  }
  function openAccountDetailModal(id) {
    const a = accById(id); if (!a) return;
    const sub = M.ACCOUNT_SUBTYPES[a.subtype]; const rows = accountFlowRows(id); let running = a.opening || 0;
    const body = rows.map(r => { const delta = sub.kind === 'asset' ? r.amount : -r.amount; running += delta; return `<tr><td>${r.date}</td><td>${esc((KIND_TAG[r.kind] || KIND_TAG.generic)[1])}</td><td>${esc(r.store || '')}${r.branch ? ' <span class="muted">/ ' + esc(r.branch) + '</span>' : ''}</td><td class="num">${yen(delta)}</td><td class="num">${yen(running)}</td><td><button class="btn ghost sm" data-jumpedit="${r.id}">編集</button></td></tr>`; }).join('');
    const bal = M.accountBalance(state, id); const neg = sub.kind === 'asset' && bal < 0 ? `<p class="excel-issues">⚠ 資産口座の残高がマイナスです。期首残高・口座統合・支払元の誤りを確認してください。</p>` : '';
    $('#modal').innerHTML = `<h3>残高詳細：${esc(a.name)}</h3><div class="excel-mini"><span class="tag">種類 ${esc(sub.label)}</span><span class="tag">期首 ${yen(a.opening || 0)}</span><span class="tag">取引 ${rows.length}件</span><span class="tag">現在 ${yen(bal)}</span></div>${neg}<div class="excel-tablewrap"><table><thead><tr><th>日付</th><th>種別</th><th>店/メモ</th><th class="num">増減</th><th class="num">残高</th><th></th></tr></thead><tbody>${body || '<tr><td colspan="6" class="muted">この口座を使う取引はありません</td></tr>'}</tbody></table></div><div class="actions"><button class="btn ghost" id="ad_close">閉じる</button></div>`;
    $('#ad_close').addEventListener('click', closeModal);
    $$('[data-jumpedit]', $('#modal')).forEach(b => b.addEventListener('click', () => { const tid = b.dataset.jumpedit; closeModal(); loadForEdit(tid); }));
    showModal();
  }
  function replaceAccountIdIn(obj, fromId, toId) {
    if (!obj) return;
    if (Array.isArray(obj)) { obj.forEach(x => replaceAccountIdIn(x, fromId, toId)); return; }
    if (typeof obj === 'object') Object.keys(obj).forEach(k => { const v = obj[k]; if (v === fromId) obj[k] = toId; else if (v === 'acc:' + fromId) obj[k] = 'acc:' + toId; else replaceAccountIdIn(v, fromId, toId); });
  }
  function openAccountMergeModal() {
    if (state.accounts.length < 2) return toast('統合するには口座が2つ以上必要です');
    const opts = state.accounts.map(a => `<option value="${a.id}">${esc(a.name)}（${M.ACCOUNT_SUBTYPES[a.subtype].label} / ${yen(M.accountBalance(state, a.id))}）</option>`).join('');
    $('#modal').innerHTML = `<h3>口座統合</h3><p class="hint">統合元口座を統合先口座へまとめます。過去取引・固定費・テンプレ・積立目標の参照も置換します。期首残高は統合先へ加算します。</p><div class="field"><label>統合元（消える口座）</label><select id="mg_from">${opts}</select></div><div class="field"><label>統合先（残す口座）</label><select id="mg_to">${opts}</select></div><div class="actions"><button class="btn ghost" id="mg_cancel">キャンセル</button><button class="btn danger" id="mg_ok">統合する</button></div>`;
    $('#mg_cancel').addEventListener('click', closeModal);
    $('#mg_ok').addEventListener('click', () => { const fromId = $('#mg_from').value, toId = $('#mg_to').value; if (fromId === toId) return toast('同じ口座には統合できません'); const from = accById(fromId), to = accById(toId); if (!from || !to) return; if (!confirm(`${from.name} を ${to.name} へ統合します。元には戻せません。よろしいですか？`)) return; to.opening = (to.opening || 0) + (from.opening || 0); replaceAccountIdIn(state.transactions, fromId, toId); replaceAccountIdIn(state.recurring, fromId, toId); replaceAccountIdIn(state.templates, fromId, toId); replaceAccountIdIn(state.goals, fromId, toId); state.accounts = state.accounts.filter(a => a.id !== fromId); persist(); closeModal(); refreshDatalists(); renderAll(); toast('口座を統合しました ✓'); });
    showModal();
  }

  function renderAccounts() {
    const assets = accountsBy(a => M.ACCOUNT_SUBTYPES[a.subtype].kind === 'asset' && a.subtype !== 'transit'); const liabs = accountsBy(a => M.ACCOUNT_SUBTYPES[a.subtype].kind === 'liability'); const maxAbs = Math.max(1, ...assets.map(a => Math.abs(M.accountBalance(state, a.id))));
    const accHtml = a => { const bal = M.accountBalance(state, a.id); const extra = a.subtype === 'voucher_goods' ? ` · 残${M.goodsQty(state, a.id)}枚` : ''; const w = Math.min(100, Math.abs(bal) / maxAbs * 100); return `<div class="acc-row"><div><div class="acc-name">${esc(a.name)}</div><div class="acc-sub">${M.ACCOUNT_SUBTYPES[a.subtype].label}${extra}</div><div class="bar"><span style="width:${w}%"></span></div></div><div class="num" style="font-weight:700">${yen(bal)}</div></div>`; };
    const totalAsset = assets.reduce((s, a) => s + M.accountBalance(state, a.id), 0); const totalLiab = liabs.reduce((s, a) => s + M.accountBalance(state, a.id), 0);
    $('#accList').innerHTML = `<div class="acc-sub" style="margin-bottom:4px">資産</div>` + assets.map(accHtml).join('') + (liabs.length ? `<div class="acc-sub" style="margin:10px 0 4px">負債</div>` + liabs.map(accHtml).join('') : ''); $('#netWorth').textContent = `純資産 ${yen(totalAsset - totalLiab)}`;
    $('#accManage').innerHTML = state.accounts.map(a => `<div class="acc-row"><div><div class="acc-name">${esc(a.name)} <span class="tag">${M.ACCOUNT_SUBTYPES[a.subtype].label}</span></div><div class="acc-sub">期首 ${yen(a.opening || 0)}${a.subtype === 'voucher_goods' ? ' · 期首枚数' + ((a.goods&&a.goods.openingQty)||0) + '枚' + (((a.goods&&a.goods.faceHistory)||[]).length ? ' · 額面履歴' + ((a.goods&&a.goods.faceHistory)||[]).length + '件' : '') : ''}${a.subtype === 'card' && a.card ? ' · 締め' + (a.card.closingDay === 99 ? '末' : a.card.closingDay + '日') + '／引落' + a.card.payDay + '日' : ''}</div></div><div class="row" style="gap:6px"><button class="btn ghost sm" data-accdetail="${a.id}">詳細</button><button class="btn ghost sm" data-edit="${a.id}">編集</button><button class="btn danger sm" data-delacc="${a.id}">削除</button></div></div>`).join('');
    $$('[data-edit]', $('#accManage')).forEach(b => b.addEventListener('click', () => openAccountModal(b.dataset.edit)));
    $$('[data-accdetail]', $('#accManage')).forEach(b => b.addEventListener('click', () => openAccountDetailModal(b.dataset.accdetail)));
    $$('[data-delacc]').forEach(b => b.addEventListener('click', () => { const used = state.transactions.some(t => t.lines.some(l => l.ref === 'acc:' + b.dataset.delacc)); if (used) return toast('この口座を使う取引があるため削除できません'); if (!confirm('口座を削除しますか？')) return; state.accounts = state.accounts.filter(a => a.id !== b.dataset.delacc); persist(); renderAccounts(); toast('削除しました'); }));
  }
  function openAccountModal(id) {
    const editing = id ? accById(id) : null; const a = editing || { name: '', subtype: 'cash', opening: 0 }; const subOpts = Object.entries(M.ACCOUNT_SUBTYPES).map(([k, v]) => `<option value="${k}" ${k === a.subtype ? 'selected' : ''}>${v.label}</option>`).join('');
    $('#modal').innerHTML = `<h3>${editing ? '口座を編集' : '口座を追加'}</h3><div class="field"><label>口座名</label><input id="m_name" value="${esc(a.name)}" placeholder="例: 楽天カード / WAON / コーヒーチケット"></div><div class="field"><label>種類</label><select id="m_sub">${subOpts}</select></div><div class="field"><label>期首残高</label><input type="number" id="m_open" value="${a.opening || 0}"></div><div id="m_extra"></div><div class="actions"><button class="btn ghost" id="m_cancel">キャンセル</button><button class="btn" id="m_save">保存</button></div>`;
    const renderExtra = () => { const sub = $('#m_sub').value, ex = $('#m_extra'); if (sub === 'card') ex.innerHTML = `<div class="row"><div class="field"><label>締め日</label><select id="m_close">${[['99', '末日'], ['15', '15日'], ['20', '20日'], ['25', '25日'], ['10', '10日'], ['5', '5日']].map(([v, l]) => `<option value="${v}" ${(a.card && String(a.card.closingDay) === v) ? 'selected' : ''}>${l}</option>`).join('')}</select></div><div class="field"><label>引落日(毎月)</label><input type="number" id="m_payday" min="1" max="31" value="${a.card?.payDay || 27}"></div><div class="field"><label>引落は締めの</label><select id="m_after"><option value="1" ${(!a.card || a.card.payMonthsAfter !== 2) ? 'selected' : ''}>翌月</option><option value="2" ${(a.card && a.card.payMonthsAfter === 2) ? 'selected' : ''}>翌々月</option></select></div></div>`; else if (sub === 'voucher_goods') { const hist=(a.goods&&a.goods.faceHistory)||[]; const histRows=hist.map((h,i)=>`<div class="credit-line face-history-row" data-i="${i}"><div class="field credit-amt-field"><label>日付</label><input type="date" class="m_face_date" value="${esc(h.date||'')}"></div><div class="field credit-amt-field"><label>1枚額面</label><input type="number" class="m_face_unit" value="${esc(h.unit||'')}"></div><button class="btn danger sm m_face_del" type="button">削除</button></div>`).join(''); ex.innerHTML = `<div class="field"><label>期首の残枚数</label><input type="number" id="m_openqty" value="${a.goods?.openingQty || 0}"></div><p class="hint">額面履歴を入れると、その日付以降は「枚数 × 1枚額面」で現物券の利用額を計算します。4月以前から持っているチケットは、期首日または 2026-04-01 などで1枚額面を登録してください。</p><div class="receipt-cards" id="m_facehist">${histRows||'<p class="muted">額面履歴なし。残高÷枚数で計算します。</p>'}</div><button class="btn ghost sm" type="button" id="m_face_add">＋額面履歴</button>`; const addRow=()=>{ const host=$('#m_facehist'); if(host.querySelector('.muted')) host.innerHTML=''; const row=el('div',{class:'credit-line face-history-row'}); row.innerHTML=`<div class="field credit-amt-field"><label>日付</label><input type="date" class="m_face_date" value="${M.todayStr()}"></div><div class="field credit-amt-field"><label>1枚額面</label><input type="number" class="m_face_unit" placeholder="例: 530"></div><button class="btn danger sm m_face_del" type="button">削除</button>`; host.appendChild(row); row.querySelector('.m_face_del').addEventListener('click',()=>row.remove()); attachHankakuAll(row); }; setTimeout(()=>{ const b=$('#m_face_add'); if(b)b.addEventListener('click',addRow); $$('.m_face_del', ex).forEach(btn=>btn.addEventListener('click',()=>btn.closest('.face-history-row').remove())); },0); } else if (sub === 'transit') ex.innerHTML = `<p class="hint">簡易モード：チャージ時に全額費用化（残高管理なし）。</p>`; else ex.innerHTML = ''; attachHankakuAll(ex); };
    renderExtra(); $('#m_sub').addEventListener('change', renderExtra); $('#m_cancel').addEventListener('click', closeModal);
    $('#m_save').addEventListener('click', () => { const name = $('#m_name').value.trim(); if (!name) return toast('口座名を入力してください'); const sub = $('#m_sub').value; const obj = editing || { id: 'a_' + Math.random().toString(36).slice(2, 8) }; obj.name = name; obj.subtype = sub; obj.opening = +$('#m_open').value || 0; if (sub === 'card') obj.card = { closingDay: +$('#m_close').value, payDay: +$('#m_payday').value || 27, payMonthsAfter: +$('#m_after').value }; if (sub === 'voucher_goods') { const faceHistory=[]; $$('#m_facehist .face-history-row').forEach(row=>{ const date=row.querySelector('.m_face_date')?.value||''; const unit=+(row.querySelector('.m_face_unit')?.value||0); if(date&&unit>0) faceHistory.push({date,unit}); }); faceHistory.sort((a,b)=>a.date.localeCompare(b.date)); obj.goods = { openingQty: +($('#m_openqty')?.value || 0), faceHistory }; } if (!editing) state.accounts.push(obj); persist(); closeModal(); renderAccounts(); renderEntry(); toast('保存しました ✓'); });
    showModal();
  }

  /* ============ カード請求 ============ */
  function renderCards() {
    const host = $('#cardCycles'); if (!host) return; const cards = accountsBy(a => a.subtype === 'card'); if (!cards.length) { host.innerHTML = `<p class="muted">カード口座がありません。「残高・口座」から追加してください。</p>`; return; }
    let html = '';
    for (const card of cards) { const cycles = M.cardCycles(state, card.id); const dueTotal = cycles.filter(c => c.due && !c.settled).reduce((s, c) => s + c.outstanding, 0); html += `<div style="margin-bottom:14px"><div class="section-title" style="margin-bottom:8px"><h3 style="margin:0">${esc(card.name)} <span class="acc-sub">未払 合計 ${yen(M.accountBalance(state, card.id))}</span></h3>${dueTotal > 0 ? `<button class="btn sm" data-payall="${card.id}">期限到来分をまとめて消込 (${yen(dueTotal)})</button>` : ''}</div>`; if (!cycles.length) html += `<p class="muted">請求はありません。</p>`; cycles.slice().reverse().forEach(c => { const badge = c.settled ? `<span class="badge ok">消込済</span>` : (c.due ? `<span class="badge due">要支払</span>` : `<span class="badge plan">予定</span>`); html += `<div class="cycle-row ${c.settled ? 'settled' : (c.due ? 'due' : '')}"><div><div class="acc-name">${c.key} 締め${badge}</div><div class="acc-sub">引落 ${c.payDate} ・ 請求 ${yen(c.charge)}${c.paid ? ' ・ 支払済 ' + yen(c.paid) : ''}</div></div><div style="text-align:right"><div class="num" style="font-weight:700">${yen(c.outstanding)}</div>${!c.settled ? `<button class="btn ghost sm" data-pay="${card.id}|${c.key}|${c.payDate}|${c.outstanding}">消込</button>` : ''}</div></div>`; }); html += `</div>`; }
    host.innerHTML = html;
    $$('[data-pay]', host).forEach(b => b.addEventListener('click', () => { const [cardId, key, payDate, out] = b.dataset.pay.split('|'); payModalContent('カード引落の消込', cardId, key, payDate, +out, payDate, [{ accId: (accountsBy(a => a.subtype === 'bank')[0] || {}).id || '', amount: Math.round(+out) }], null); showModal(); }));
    $$('[data-payall]', host).forEach(b => b.addEventListener('click', () => payAllDue(b.dataset.payall)));
  }
  function payModalContent(title, cardId, cycleKey, payDate, outstanding, date, credits, editId) {
    ui._payCredits = credits.map(c => ({ ...c }));
    const draw = () => { const opts = sel => accountOptions(a => ['bank', 'cash', 'point', 'emoney'].includes(a.subtype), sel); const rows = ui._payCredits.map((c, i) => `<div class="credit-line" data-i="${i}"><div class="field" style="flex:2"><select class="pc_acc">${opts(c.accId)}</select></div><div class="field amt"><input type="number" class="pc_amt" value="${c.amount}"></div><button class="btn ghost sm pc_del">✕</button></div>`).join(''); const sum = ui._payCredits.reduce((s, c) => s + (+c.amount || 0), 0); const diff = outstanding - sum; const matched = Math.abs(diff) < 0.5;
      $('#modal').innerHTML = `<h3>${title}</h3><p class="hint">${esc(accName(cardId))} / ${cycleKey}締め ・ 請求残 <b>${yen(outstanding)}</b>。銀行＋ポイント等の複数充当が可能です。</p><div class="field"><label>引落日</label><input type="date" id="pay_date" value="${date}"></div><label>支払元（複数可）</label>${rows}<button class="btn ghost sm" id="pay_add">＋支払元を追加</button><div class="totline"><span>支払合計 <span class="muted" id="pay_diff"></span></span><span class="v" id="pay_sum">${yen(sum)}</span></div><div class="balance-warn" id="pay_warn"></div><div class="actions"><button class="btn ghost" id="pay_cancel">キャンセル</button>${matched ? '' : `<button class="btn ghost sm" id="pay_fill">残額を自動補充</button>`}<button class="btn" id="pay_ok" ${matched ? '' : 'disabled'}>${editId ? '更新' : '消込する'}</button></div>`;
      $('#pay_sum').style.color = matched ? 'var(--accent2)' : 'var(--warn)'; $('#pay_diff').innerHTML = matched ? '（一致）' : `（差 ${yen(diff)}）`; $('#pay_warn').textContent = matched ? '' : `⚠ 支払合計が請求残 ${yen(outstanding)} と一致していません。一致させると消込できます（分割払いは未対応）。`;
      $$('#modal .credit-line').forEach(line => { const i = +line.dataset.i; line.querySelector('.pc_acc').addEventListener('change', e => ui._payCredits[i].accId = e.target.value); line.querySelector('.pc_amt').addEventListener('input', e => { ui._payCredits[i].amount = +e.target.value; draw(); }); line.querySelector('.pc_del').addEventListener('click', () => { ui._payCredits.splice(i, 1); if (!ui._payCredits.length) ui._payCredits.push({ accId: '', amount: 0 }); draw(); }); });
      $('#pay_add').addEventListener('click', () => { const rest = outstanding - ui._payCredits.reduce((s, c) => s + (+c.amount || 0), 0); ui._payCredits.push({ accId: (accountsBy(a => a.subtype === 'point')[0] || {}).id || '', amount: Math.max(0, Math.round(rest)) }); draw(); });
      const pf = $('#pay_fill'); if (pf) pf.addEventListener('click', () => { const rest = outstanding - ui._payCredits.reduce((s, c) => s + (+c.amount || 0), 0); if (ui._payCredits.length) ui._payCredits[ui._payCredits.length - 1].amount = (+ui._payCredits[ui._payCredits.length - 1].amount || 0) + Math.round(rest); else ui._payCredits.push({ accId: (accountsBy(a => a.subtype === 'bank')[0] || {}).id || '', amount: Math.round(rest) }); draw(); });
      $('#pay_cancel').addEventListener('click', closeModal);
      $('#pay_ok').addEventListener('click', () => { const creds = ui._payCredits.map(c => ({ accId: c.accId, amount: +c.amount })).filter(c => c.accId && c.amount); if (!creds.length) return toast('支払元を入力してください'); const cs = creds.reduce((s, c) => s + c.amount, 0); if (Math.abs(cs - outstanding) > 0.5) return toast('支払合計が請求残と一致していません'); const t = M.buildCardPayment({ id: editId, date: $('#pay_date').value, cardAccId: cardId, credits: creds, cycleKey, payDate: $('#pay_date').value }); if (editId) { const idx = state.transactions.findIndex(x => x.id === editId); if (idx >= 0) state.transactions[idx] = t; toast('更新しました ✓'); } else { state.transactions.push(t); toast('消込しました ✓'); } persist(); closeModal(); renderCards(); renderAccounts(); renderList(); renderDrill(); });
    };
    draw();
  }
  function payAllDue(cardId) { const bank = accountsBy(a => a.subtype === 'bank')[0] || accountsBy(a => a.subtype === 'cash')[0]; if (!bank) return toast('引落元の銀行/現金口座がありません'); const due = M.cardCycles(state, cardId).filter(c => c.due && !c.settled); if (!due.length) return toast('期限到来分はありません'); if (!confirm(`${due.length}件の請求を ${bank.name} からまとめて消込します。よろしいですか？`)) return; due.forEach(c => state.transactions.push(M.buildCardPayment({ date: c.payDate, cardAccId: cardId, credits: [{ accId: bank.id, amount: c.outstanding }], cycleKey: c.key, payDate: c.payDate }))); persist(); renderCards(); renderAccounts(); renderList(); toast(`${due.length}件を消込しました ✓`); }

