  /* ============ 設定：固定費 ============ */
  const INTERVAL_LABEL = { 1: '毎月', 2: '隔月', 3: '3か月ごと', 6: '半年ごと', 12: '年1回' };
  const BIZ_LABEL = { none: 'そのまま', next: '翌営業日', prev: '前営業日' };
  function renderRecList() { const host = $('#recList'); if (!host) return; if (!state.recurring.length) { host.innerHTML = `<p class="muted">まだテンプレがありません。</p>`; return; } host.innerHTML = state.recurring.map(r => { const iv = r.intervalMonths || 1; const ivl = INTERVAL_LABEL[iv] || (iv + 'か月ごと'); const biz = (r.bizAdjust && r.bizAdjust !== 'none') ? '・土日祝→' + BIZ_LABEL[r.bizAdjust] : ''; return `<div class="rec-row"><div class="rn"><div class="acc-name">${esc(r.name)} ${r.active === false ? '<span class="tag">停止中</span>' : ''} ${iv > 1 ? '<span class="tag">' + ivl + '</span>' : ''} ${r.bizAdjust && r.bizAdjust !== 'none' ? '<span class="tag">' + BIZ_LABEL[r.bizAdjust] + '</span>' : ''}</div><div class="acc-sub">${r.builder === 'income' ? '定期収入' : '固定費'} ・ 毎月${r.dayOfMonth}日 ・ ${ivl}${iv > 1 && r.anchorYM ? '(基準' + r.anchorYM + ')' : ''}${biz} ・ ${r.params.catPath.replace(/^exp>|^inc>/, '').split('>').join(' › ')} ・ ${accName(r.params.accId)}${r.lastApplied ? ' ・ 最終 ' + r.lastApplied : ''}</div></div><div class="rec-amt">${yen(r.params.amount)}</div><div class="row" style="gap:6px"><button class="btn ghost sm" data-recedit="${r.id}">編集</button><button class="btn danger sm" data-recdel="${r.id}">削除</button></div></div>`; }).join(''); $$('[data-recedit]', host).forEach(b => b.addEventListener('click', () => openRecModal(b.dataset.recedit))); $$('[data-recdel]', host).forEach(b => b.addEventListener('click', () => { if (!confirm('テンプレを削除しますか？')) return; state.recurring = state.recurring.filter(r => r.id !== b.dataset.recdel); persist(); renderRecList(); updateGlobalNotice(); })); }
  function openRecModal(id) {
    const editing = id ? state.recurring.find(r => r.id === id) : null; const r = editing || { id: 'r_' + Math.random().toString(36).slice(2, 8), name: '', dayOfMonth: 1, active: true, lastApplied: null, intervalMonths: 1, anchorYM: null, bizAdjust: 'none', builder: 'expense', params: { catPath: 'exp>住居>家賃', amount: 0, accId: (accountsBy(a => a.subtype === 'bank')[0] || {}).id || '' } };
    const draw = () => { const kind = r.builder === 'income' ? 'income' : 'expense'; const iv = r.intervalMonths || 1;
      $('#modal').innerHTML = `<h3>${editing ? 'テンプレを編集' : 'テンプレを追加'}</h3><div class="row"><div class="field" style="flex:2"><label>名称</label><input id="rc_name" value="${esc(r.name)}" placeholder="例: 家賃 / Netflix / 給与 / 水道代"></div><div class="field"><label>種別</label><select id="rc_builder"><option value="expense" ${r.builder !== 'income' ? 'selected' : ''}>固定費</option><option value="income" ${r.builder === 'income' ? 'selected' : ''}>定期収入</option></select></div></div><div class="row"><div class="field"><label>毎月の日</label><input type="number" id="rc_day" min="1" max="31" value="${r.dayOfMonth}"></div><div class="field"><label>金額（基準）</label><input type="number" id="rc_amt" value="${r.params.amount}"></div><div class="field"><label>周期</label><select id="rc_iv">${Object.entries(INTERVAL_LABEL).map(([v, l]) => `<option value="${v}" ${iv == v ? 'selected' : ''}>${l}</option>`).join('')}</select></div></div><div class="row"><div class="field" id="rc_anchorWrap" ${iv > 1 ? '' : 'style="display:none"'}><label>基準月</label><input type="month" id="rc_anchor" value="${r.anchorYM || M.curYM()}"></div><div class="field"><label>土日祝の場合</label><select id="rc_biz">${Object.entries(BIZ_LABEL).map(([v, l]) => `<option value="${v}" ${(r.bizAdjust || 'none') === v ? 'selected' : ''}>${l}</option>`).join('')}</select></div></div><div class="field"><label>カテゴリ</label><select id="rc_cat" class="catsel">${categoryOptions(kind, r.params.catPath)}</select></div><div class="field"><label>${r.builder === 'income' ? '入金先口座' : '支払元口座'}</label><select id="rc_acc">${accountOptions(a => r.builder === 'income' ? (M.ACCOUNT_SUBTYPES[a.subtype].kind === 'asset') : true, r.params.accId)}</select></div><div class="field"><label><input type="checkbox" id="rc_active" ${r.active !== false ? 'checked' : ''} style="width:auto"> 有効</label></div><div class="actions"><button class="btn ghost" id="rc_cancel">キャンセル</button><button class="btn" id="rc_save">保存</button></div>`;
      $('#rc_builder').addEventListener('change', e => { r.builder = e.target.value; r.params.catPath = e.target.value === 'income' ? 'inc>給与' : 'exp>住居>家賃'; r.params.accId = $('#rc_acc').value; draw(); }); $('#rc_iv').addEventListener('change', e => { r.intervalMonths = +e.target.value; $('#rc_anchorWrap').style.display = (+e.target.value > 1) ? '' : 'none'; }); $('#rc_cancel').addEventListener('click', closeModal); decorateInputs($('#modal'));
      $('#rc_save').addEventListener('click', () => { const name = $('#rc_name').value.trim(); if (!name) return toast('名称を入力してください'); const obj = editing || r; obj.name = name; obj.builder = $('#rc_builder').value; obj.dayOfMonth = +$('#rc_day').value || 1; obj.intervalMonths = +$('#rc_iv').value; obj.anchorYM = obj.intervalMonths > 1 ? ($('#rc_anchor').value || M.curYM()) : null; obj.bizAdjust = $('#rc_biz').value; obj.active = $('#rc_active').checked; obj.params = { catPath: $('#rc_cat').value, amount: +$('#rc_amt').value || 0, accId: $('#rc_acc').value }; if (!editing) state.recurring.push(obj); persist(); closeModal(); renderRecList(); updateGlobalNotice(); toast('保存しました ✓'); });
    };
    draw(); showModal();
  }
  function updateGlobalNotice() { const host = $('#globalNotice'); if (!host) return; const pend = M.pendingRecurring(state, currentYM()); if (!pend.length) { host.innerHTML = ''; return; } host.innerHTML = `<div class="notice"><span>📌 未登録の固定費・定期収入が <b>${pend.length}件</b> あります（${currentYM()}まで）。</span><button class="btn sm" id="openApply">まとめて登録</button></div>`; $('#openApply').addEventListener('click', () => openApplyModal(pend)); }
  function openApplyModal(pend) {
    $('#modal').innerHTML = `<h3>固定費・定期収入の登録</h3><p class="hint">登録する項目にチェック。金額・日付はその都度調整できます（既定日付は営業日調整済み）。</p><div id="applyRows">${pend.map((p, i) => `<div class="apply-row" data-i="${i}"><input type="checkbox" class="ap_on" checked><span class="an">${esc(p.rec.name)} <span class="acc-sub">${p.ym} ・ ${p.rec.builder === 'income' ? '収入' : '費用'}</span></span><input type="date" class="ap_date" value="${p.date}"><input type="number" class="ap_amt" value="${p.rec.params.amount}"></div>`).join('')}</div><div class="actions"><button class="btn ghost" id="ap_cancel">キャンセル</button><button class="btn" id="ap_ok">登録する</button></div>`;
    $('#ap_cancel').addEventListener('click', closeModal);
    $('#ap_ok').addEventListener('click', () => { const applied = {}; $$('#applyRows .apply-row').forEach(row => { const i = +row.dataset.i; if (!row.querySelector('.ap_on').checked) return; const amt = +row.querySelector('.ap_amt').value; const date = row.querySelector('.ap_date').value; const p = pend[i]; state.transactions.push(M.buildFromRecurring(p.rec, p.ym, amt, date)); if (!applied[p.rec.id] || applied[p.rec.id] < p.ym) applied[p.rec.id] = p.ym; }); Object.entries(applied).forEach(([rid, ym]) => { const r = state.recurring.find(x => x.id === rid); if (r && (!r.lastApplied || r.lastApplied < ym)) r.lastApplied = ym; }); persist(); closeModal(); refreshDatalists(); renderAll(); updateGlobalNotice(); toast('固定費を登録しました ✓'); });
    showModal();
  }
  let settingsSection = 'rec';
  function renderSettingsTabs() { const host = $('#settingsSubtabs'); if (!host) return; $$('#settingsSubtabs button').forEach(b => b.classList.toggle('active', b.dataset.setting === settingsSection)); $$('[data-setting-panel]', $('#tab-settings')).forEach(p => p.hidden = p.dataset.settingPanel !== settingsSection); }
  function renderThemeSettings() { const preset = $('#themePreset'), accent = $('#themeAccent'), preview = $('#themePreview'); if (!preset || !accent) return; const t = loadTheme(); preset.value = t.preset || 'midnight'; accent.value = t.accent || '#4f9dff'; const redraw = () => { const nt = { preset: preset.value, accent: accent.value }; saveTheme(nt); applyTheme(nt); if (preview) preview.innerHTML = `<div class="stat"><div class="k">Preview</div><div class="v pos">${THEME_PRESETS[preset.value]?.label || preset.value}</div><div class="sub">Accent ${accent.value}</div></div><button class="btn sm">ボタン</button><span class="tag">タグ</span>`; }; preset.oninput = redraw; accent.oninput = redraw; const reset = $('#themeReset'); if (reset) reset.onclick = () => { saveTheme({ preset: 'midnight', accent: '#4f9dff' }); applyTheme(); renderThemeSettings(); }; redraw(); }
  function renderSettings() { renderSettingsTabs(); renderThemeSettings(); renderCatTree(); renderRecList(); renderTplList(); renderReadings(); $('#dl-top').innerHTML = Object.keys(state.categories.expense).map(s => `<option value="${esc(s)}">`).join(''); }
  function renderCatTree() {
    const kind = $('#catKind').value;
    const q = ($('#catSearch') ? $('#catSearch').value : '').trim();
    const rows = categoryRows(kind).filter(r => !q || r.label.includes(q) || r.path.includes(q));
    const stats = categoryUsageStats(kind);
    const bar = `<div class="cat-toolbar"><div class="field" style="margin:0;min-width:180px"><label>カテゴリ検索</label><input id="catSearch" value="${esc(q)}" placeholder="例: 食費 / 税金"></div><button class="btn ghost sm" id="catAddTop">＋大カテゴリ</button><button class="btn ghost sm" id="catMergeBtn">カテゴリ統合</button><button class="btn ghost sm" id="catSplitBtn">カテゴリ分割</button><div class="acc-sub">件数と金額は配下込み。＋で一覧内へ挿入できます。</div></div>`;
    const body = rows.map(r => { const st = stats[r.path] || { count:0, amount:0 }; const used = catIsUsed(r.path); const canUp = canMoveCategory(r.path, -1), canDown = canMoveCategory(r.path, 1); const child = nextChildLevel(r); const childBtn = child ? `<button class="btn ghost sm" data-cataddchild="${esc(r.path)}">＋${child}</button>` : ''; return `<div class="cat-row level-${r.level} ${used?'':'unused'}"><div class="cat-name" title="${esc(r.path)}">${esc(r.name)}<div class="cat-meta">${esc(r.label)}</div></div><div class="cat-meta">${st.count}件 / ${yen(st.amount)}</div><div class="cat-meta">${used?'使用中':'未使用'}</div><div class="cat-actions"><button class="btn ghost sm" data-catopen="${esc(r.path)}">取引一覧</button>${childBtn}<button class="btn ghost sm" data-cataddsibling="${esc(r.path)}">＋同階層</button><button class="btn ghost sm" data-catren="${esc(r.path)}">名称変更</button><button class="btn ghost sm" data-catup="${esc(r.path)}" ${canUp?'':'disabled'}>↑</button><button class="btn ghost sm" data-catdown="${esc(r.path)}" ${canDown?'':'disabled'}>↓</button><button class="btn ghost sm" data-catmerge="${esc(r.path)}">統合</button><button class="btn ghost sm" data-catsplit="${esc(r.path)}">分割</button><button class="btn danger sm" data-catdel="${esc(r.path)}" ${used?'disabled':''}>削除</button></div></div>`; }).join('') || '<p class="muted">カテゴリなし</p>';
    $('#catTree').innerHTML = `<div class="cat-manager">${bar}<div>${body}</div></div>`;
    const cs = $('#catSearch'); if (cs) cs.addEventListener('input', renderCatTree);
    $('#catAddTop').addEventListener('click', () => openCategoryAddModal({ kind, level: 0 }));
    $('#catMergeBtn').addEventListener('click', () => openCategoryMergeModal(null));
    $('#catSplitBtn').addEventListener('click', () => openCategorySplitModal(null));
    $$('[data-catopen]', $('#catTree')).forEach(b => b.addEventListener('click', () => { const row = categoryRows(kind).find(r => r.path === b.dataset.catopen); gotoListWithCategory(b.dataset.catopen, row ? row.label : b.dataset.catopen); }));
    $$('[data-cataddchild]', $('#catTree')).forEach(b => b.addEventListener('click', () => openCategoryAddModal({ kind, parentPath: b.dataset.cataddchild, level: b.dataset.cataddchild.split('>').length - 1 })));
    $$('[data-cataddsibling]', $('#catTree')).forEach(b => b.addEventListener('click', () => openCategoryAddModal({ kind, siblingPath: b.dataset.cataddsibling, level: b.dataset.cataddsibling.split('>').length - 2 })));
    $$('[data-catren]', $('#catTree')).forEach(b => b.addEventListener('click', () => openCategoryRenameModal(b.dataset.catren)));
    $$('[data-catdel]', $('#catTree')).forEach(b => b.addEventListener('click', () => { if (confirm('この未使用カテゴリを削除しますか？')) deleteUnusedCategory(b.dataset.catdel); }));
    $$('[data-catup]', $('#catTree')).forEach(b => b.addEventListener('click', () => moveCategory(b.dataset.catup, -1)));
    $$('[data-catdown]', $('#catTree')).forEach(b => b.addEventListener('click', () => moveCategory(b.dataset.catdown, 1)));
    $$('[data-catmerge]', $('#catTree')).forEach(b => b.addEventListener('click', () => openCategoryMergeModal(b.dataset.catmerge)));
    $$('[data-catsplit]', $('#catTree')).forEach(b => b.addEventListener('click', () => openCategorySplitModal(b.dataset.catsplit)));
  }
  function nextChildLevel(r){ if(r.path.startsWith('inc>')) return null; return r.level===0?'中':(r.level===1?'小':null); }
  function categoryRows(kind){const out=[];const root=state.categories[kind]||{};const pfx=kind==='income'?'inc':'exp';Object.keys(root).forEach(top=>{out.push({path:pfx+'>'+top,label:top,name:top,level:0});const mids=root[top]||{};Object.keys(mids).forEach(mid=>{out.push({path:pfx+'>'+top+'>'+mid,label:top+' › '+mid,name:mid,level:1});(mids[mid]||[]).forEach(leaf=>out.push({path:pfx+'>'+top+'>'+mid+'>'+leaf,label:top+' › '+mid+' › '+leaf,name:leaf,level:2}));});});return out;}
  function categoryPaths(kind){return categoryRows(kind).map(r=>({path:r.path,label:r.label}));}
  function categoryUsageStats(kind){const rows=categoryRows(kind);const stats={};rows.forEach(r=>stats[r.path]={count:0,amount:0,refs:0});const pfx=kind==='income'?'inc>':'exp>';state.transactions.forEach(t=>{const seen=new Set();t.lines.forEach(l=>{if(!l.ref.startsWith('cat:'+pfx))return;const path=l.ref.slice(4);const amount=kind==='income'?-l.amount:l.amount;if(amount<=0)return;rows.forEach(r=>{if(path===r.path||path.startsWith(r.path+'>')){stats[r.path].amount+=amount;stats[r.path].refs++;seen.add(r.path);}});});seen.forEach(p=>stats[p].count++);});return stats;}
  function catIsUsed(path){const full='cat:'+path,pref=full+'>';if(state.transactions.some(t=>t.lines.some(l=>l.ref===full||l.ref.startsWith(pref))))return true;if(Object.keys(state.budgets||{}).some(k=>k===path||k.startsWith(path+'>')))return true;if((state.recurring||[]).some(r=>r.params&&r.params.catPath&&(r.params.catPath===path||r.params.catPath.startsWith(path+'>'))))return true;if((state.templates||[]).some(t=>(t.items||[]).some(it=>it.catPath&&(it.catPath===path||it.catPath.startsWith(path+'>')))))return true;return false;}
  function ensureCatMaps(kind){ if(!state.categories[kind]) state.categories[kind]={}; return state.categories[kind]; }
  function insertObjectKey(obj, key, value, afterKey){ const nr={}; let done=false; Object.keys(obj).forEach(k=>{nr[k]=obj[k]; if(k===afterKey){nr[key]=value; done=true;}}); if(!done) nr[key]=value; Object.keys(obj).forEach(k=>delete obj[k]); Object.assign(obj,nr); }
  function createCategoryPath(kind, name, opt={}){ name=(name||'').trim(); if(!name) return null; const root=ensureCatMaps(kind); const pfx=kind==='income'?'inc':'exp'; if(kind==='income'||opt.level===0){ if(root[name]) throw new Error('同名カテゴリがあります'); insertObjectKey(root,name,{},opt.afterName); return pfx+'>'+name; } const parts=(opt.parentPath||opt.siblingPath||'').split('>'); const top=parts[1]; if(!top||!root[top]) throw new Error('親カテゴリがありません'); if(opt.level===1){ if(root[top][name]) throw new Error('同名カテゴリがあります'); insertObjectKey(root[top],name,[],opt.afterName); return pfx+'>'+top+'>'+name; } const mid=parts[2]; if(!mid||!root[top][mid]) throw new Error('親カテゴリがありません'); const arr=root[top][mid]; if(arr.includes(name)) throw new Error('同名カテゴリがあります'); const i=opt.afterName?arr.indexOf(opt.afterName):-1; arr.splice(i>=0?i+1:arr.length,0,name); return pfx+'>'+top+'>'+mid+'>'+name; }
  function openCategoryAddModal(opt={}){ const kind=opt.kind||$('#catKind').value; const sibling=opt.siblingPath?opt.siblingPath.split('>'):null; let level=opt.level==null?0:opt.level; let parentPath=opt.parentPath||''; let afterName=sibling?sibling[sibling.length-1]:''; if(sibling){ if(level===1) parentPath=sibling.slice(0,2).join('>'); else if(level===2) parentPath=sibling.slice(0,3).join('>'); }
    const title=level===0?'大カテゴリ追加':(level===1?'中カテゴリ追加':'小カテゴリ追加'); $('#modal').innerHTML=`<h3>${title}</h3><p class="hint">一覧内の＋から追加した場合は、その位置の直後に挿入します。</p><div class="field"><label>カテゴリ名</label><input id="ca_name" placeholder="カテゴリ名"></div><div class="actions"><button class="btn ghost" id="ca_cancel">キャンセル</button><button class="btn" id="ca_ok">追加</button></div>`; $('#ca_cancel').addEventListener('click',closeModal); $('#ca_ok').addEventListener('click',()=>{try{const path=createCategoryPath(kind,$('#ca_name').value,{level,parentPath,siblingPath:opt.siblingPath,afterName}); if(!path)return toast('カテゴリ名を入力してください'); persist(); closeModal(); renderCatTree(); renderEntry(); refreshDatalists(); toast('カテゴリを追加しました ✓');}catch(e){toast(e.message);}}); showModal(); }
  function addCategory(){ const kind=$('#catKind').value, top=$('#catTop').value.trim(), mid=$('#catMid').value.trim(), leaf=$('#catLeaf').value.trim(); try{ if(!top) return toast('大カテゴリは必須です'); const root=ensureCatMaps(kind); if(!root[top]) root[top]={}; if(kind==='expense'&&mid){ if(!root[top][mid]) root[top][mid]=[]; if(leaf&&!root[top][mid].includes(leaf)) root[top][mid].push(leaf); } persist(); renderCatTree(); refreshDatalists(); renderEntry(); $('#catTop').value=''; $('#catMid').value=''; $('#catLeaf').value=''; toast('カテゴリを追加しました ✓'); }catch(e){toast(e.message);} }
  function mergeDuplicateCategoryLines(t){ const out=[], map={}; t.lines.forEach(l=>{ if(l.ref.startsWith('cat:')){ const k=l.ref+'|'+(l.amount>0?'d':'c'); if(map[k]) map[k].amount+=l.amount; else {map[k]={...l}; out.push(map[k]);} } else out.push(l); }); t.lines=out.filter(l=>Math.abs(l.amount)>0.0001); }
  function replaceCatRefs(oldPath,newPath,collapse=false){const oldRef='cat:'+oldPath,newRef='cat:'+newPath;state.transactions.forEach(t=>{t.lines.forEach(l=>{if(l.ref===oldRef||l.ref.startsWith(oldRef+'>'))l.ref=collapse?newRef:newRef+l.ref.slice(oldRef.length);});mergeDuplicateCategoryLines(t);});const nb={};Object.entries(state.budgets||{}).forEach(([k,v])=>{const nk=(k===oldPath||k.startsWith(oldPath+'>'))?(collapse?newPath:newPath+k.slice(oldPath.length)):k;nb[nk]=(nb[nk]||0)+v;});state.budgets=nb;(state.recurring||[]).forEach(r=>{if(r.params&&r.params.catPath&&(r.params.catPath===oldPath||r.params.catPath.startsWith(oldPath+'>')))r.params.catPath=collapse?newPath:newPath+r.params.catPath.slice(oldPath.length);});(state.templates||[]).forEach(t=>(t.items||[]).forEach(it=>{if(it.catPath&&(it.catPath===oldPath||it.catPath.startsWith(oldPath+'>')))it.catPath=collapse?newPath:newPath+it.catPath.slice(oldPath.length);}));}
  function renameCategoryDef(oldPath,newName){const parts=oldPath.split('>');const kind=parts[0]==='inc'?'income':'expense';const root=state.categories[kind];const np=parts.slice();np[np.length-1]=newName;const newPath=np.join('>');if(oldPath===newPath)return;if(kind==='income'){if(root[newName])return toast('同名カテゴリがあります');root[newName]=root[parts[1]]||{};delete root[parts[1]];}else{const top=parts[1],mid=parts[2],leaf=parts[3];if(parts.length===2){if(root[newName])return toast('同名カテゴリがあります');root[newName]=root[top]||{};delete root[top];}else if(parts.length===3){if(root[top][newName])return toast('同名カテゴリがあります');root[top][newName]=root[top][mid]||[];delete root[top][mid];}else{const arr=root[top][mid]||[];if(arr.includes(newName))return toast('同名カテゴリがあります');const i=arr.indexOf(leaf);if(i>=0)arr[i]=newName;}}replaceCatRefs(oldPath,newPath,false);persist();refreshDatalists();renderAll();toast('カテゴリ名を変更しました ✓');}
  function removeCategoryDef(path){const parts=path.split('>');const kind=parts[0]==='inc'?'income':'expense';const root=state.categories[kind];if(kind==='income')delete root[parts[1]];else{const top=parts[1],mid=parts[2],leaf=parts[3];if(parts.length===2)delete root[top];else if(parts.length===3)delete root[top][mid];else{const arr=root[top][mid]||[];const i=arr.indexOf(leaf);if(i>=0)arr.splice(i,1);}}}
  function deleteUnusedCategory(path){if(catIsUsed(path))return toast('使用中のカテゴリは削除できません');removeCategoryDef(path);persist();renderCatTree();renderEntry();renderDrill();renderBudget();toast('未使用カテゴリを削除しました ✓');}
  function siblingInfo(path){const parts=path.split('>');const kind=parts[0]==='inc'?'income':'expense';const root=state.categories[kind];if(kind==='income'||parts.length===2)return {arr:Object.keys(root), set:arr=>{const nr={};arr.forEach(k=>nr[k]=root[k]);state.categories[kind]=nr;}, key:parts[1]};if(parts.length===3){const top=parts[1];return {arr:Object.keys(root[top]||{}), set:arr=>{const old=root[top]||{}, nr={};arr.forEach(k=>nr[k]=old[k]);root[top]=nr;}, key:parts[2]};}const top=parts[1],mid=parts[2];return {arr:(root[top]&&root[top][mid])||[], set:arr=>{root[top][mid]=arr.slice();}, key:parts[3]};}
  function canMoveCategory(path,dir){const s=siblingInfo(path);const i=s.arr.indexOf(s.key);return i>=0&&i+dir>=0&&i+dir<s.arr.length;}
  function moveCategory(path,dir){const s=siblingInfo(path);const arr=s.arr.slice();const i=arr.indexOf(s.key);if(i<0||i+dir<0||i+dir>=arr.length)return;[arr[i],arr[i+dir]]=[arr[i+dir],arr[i]];s.set(arr);persist();renderCatTree();renderEntry();renderDrill();renderBudget();toast('カテゴリ順を変更しました');}
  function openCategoryRenameModal(path){const kind=$('#catKind').value;const opts=categoryPaths(kind).map(c=>`<option value="${esc(c.path)}" ${c.path===path?'selected':''}>${esc(c.label)}</option>`).join('');$('#modal').innerHTML=`<h3>カテゴリ名変更</h3><p class="hint">既存取引・予算・固定費・テンプレも追従します。</p><div class="field"><label>対象カテゴリ</label><select id="cr_path">${opts}</select></div><div class="field"><label>新しい名前（この階層名のみ）</label><input id="cr_name"></div><div class="actions"><button class="btn ghost" id="cr_cancel">キャンセル</button><button class="btn" id="cr_ok">変更</button></div>`;const fill=()=>{$('#cr_name').value=$('#cr_path').value.split('>').pop();};$('#cr_path').addEventListener('change',fill);fill();$('#cr_cancel').addEventListener('click',closeModal);$('#cr_ok').addEventListener('click',()=>{const n=$('#cr_name').value.trim();if(!n)return toast('新しい名前を入力してください');renameCategoryDef($('#cr_path').value,n);closeModal();});showModal();}
  function openCategoryDeleteModal(){const kind=$('#catKind').value;const list=categoryPaths(kind).filter(c=>!catIsUsed(c.path));if(!list.length)return toast('削除できる未使用カテゴリがありません');$('#modal').innerHTML=`<h3>未使用カテゴリ削除</h3><div class="field"><label>削除対象</label><select id="cd_path">${list.map(c=>`<option value="${esc(c.path)}">${esc(c.label)}</option>`).join('')}</select></div><div class="actions"><button class="btn ghost" id="cd_cancel">キャンセル</button><button class="btn danger" id="cd_ok">削除</button></div>`;$('#cd_cancel').addEventListener('click',closeModal);$('#cd_ok').addEventListener('click',()=>{if(confirm('この未使用カテゴリを削除しますか？')){deleteUnusedCategory($('#cd_path').value);closeModal();}});showModal();}
  function openCategoryMergeModal(fromPath){const kind=$('#catKind').value;const paths=categoryPaths(kind);if(paths.length<2)return toast('統合にはカテゴリが2つ以上必要です');const opt=p=>paths.map(c=>`<option value="${esc(c.path)}" ${c.path===p?'selected':''}>${esc(c.label)}</option>`).join('');$('#modal').innerHTML=`<h3>カテゴリ統合</h3><p class="hint">統合元カテゴリ配下の取引・予算・固定費・テンプレを統合先へ付け替え、統合元カテゴリを削除します。</p><div class="field"><label>統合元</label><select id="cm_from">${opt(fromPath)}</select></div><div class="field"><label>統合先</label><select id="cm_to">${opt('')}</select></div><div class="actions"><button class="btn ghost" id="cm_cancel">キャンセル</button><button class="btn danger" id="cm_ok">統合する</button></div>`;$('#cm_cancel').addEventListener('click',closeModal);$('#cm_ok').addEventListener('click',()=>{const from=$('#cm_from').value,to=$('#cm_to').value;if(!from||!to||from===to)return toast('統合元と統合先を確認してください');if(to.startsWith(from+'>'))return toast('配下カテゴリへは統合できません');if(!confirm('統合すると元カテゴリは削除されます。よろしいですか？'))return;replaceCatRefs(from,to,true);removeCategoryDef(from);persist();closeModal();refreshDatalists();renderAll();toast('カテゴリを統合しました ✓');});showModal();}
  function splitCandidateLines(path){const full='cat:'+path,pref=full+'>';const out=[];state.transactions.forEach(t=>t.lines.forEach((l,i)=>{if(l.ref===full||l.ref.startsWith(pref)){const amount=l.amount>0?l.amount:-l.amount;if(amount>0)out.push({tx:t,lineIndex:i,date:t.date,store:t.store,memo:t.memo,amount});}}));return out;}
  function openCategorySplitModal(path){const kind=$('#catKind').value;const paths=categoryPaths(kind);if(!path)path=paths[0]?.path;if(!path)return toast('カテゴリがありません');const srcOpts=paths.map(c=>`<option value="${esc(c.path)}" ${c.path===path?'selected':''}>${esc(c.label)}</option>`).join('');let rows=splitCandidateLines(path).slice(0,80);$('#modal').innerHTML=`<h3>カテゴリ分割</h3><p class="hint">新しいカテゴリを作り、選択した取引明細だけを新カテゴリへ移動します。金額の一部分割は次以降に回します。</p><div class="field"><label>分割元カテゴリ</label><select id="cs_from">${srcOpts}</select></div><div class="field"><label>新カテゴリ名</label><input id="cs_new" placeholder="例: その他から分ける名前"></div><div class="field"><label>作成場所</label><select id="cs_place"><option value="sibling">分割元と同じ階層</option><option value="child">分割元の配下</option></select></div><div class="excel-tablewrap" style="max-height:300px;overflow:auto"><table><thead><tr><th>対象</th><th>日付</th><th>店/メモ</th><th class="num">金額</th></tr></thead><tbody id="cs_rows">${rows.map((r,i)=>`<tr><td><input type="checkbox" class="cs_on" data-i="${i}" style="width:auto"></td><td>${r.date}</td><td>${esc(r.store||r.memo||'')}</td><td class="num">${yen(r.amount)}</td></tr>`).join('')||'<tr><td colspan="4" class="muted">対象取引がありません</td></tr>'}</tbody></table></div><div class="actions"><button class="btn ghost" id="cs_cancel">キャンセル</button><button class="btn" id="cs_ok">分割する</button></div>`;$('#cs_from').addEventListener('change',()=>{closeModal();openCategorySplitModal($('#cs_from').value);});$('#cs_cancel').addEventListener('click',closeModal);$('#cs_ok').addEventListener('click',()=>{const from=$('#cs_from').value,name=$('#cs_new').value.trim();if(!name)return toast('新カテゴリ名を入力してください');try{const parts=from.split('>');const place=$('#cs_place').value;let level,parentPath,siblingPath;if(place==='child'&&parts[0]==='exp'&&parts.length<4){level=parts.length-1;parentPath=from;}else{level=parts.length-2;siblingPath=from;}const newPath=createCategoryPath(kind,name,{level,parentPath,siblingPath,afterName:parts[parts.length-1]});const picks=[...$$('.cs_on:checked')].map(x=>rows[+x.dataset.i]);picks.forEach(r=>{r.tx.lines[r.lineIndex].ref='cat:'+newPath;mergeDuplicateCategoryLines(r.tx);});persist();closeModal();refreshDatalists();renderAll();toast(`カテゴリを分割しました ✓ ${picks.length}件移動`);}catch(e){toast(e.message);}});showModal();}
  function renderReadings() {
    const host = $('#readingList'); if (!host) return; const entries = Object.entries(state.readings || {});
    host.innerHTML = entries.length ? entries.sort((a, b) => a[0].localeCompare(b[0], 'ja')).map(([k, v]) => `<div class="reading-row"><span class="rk">${esc(k)}</span><span class="ry">${esc(v)}</span><div class="row" style="gap:6px"><button class="btn ghost sm" data-rdedit="${esc(k)}">編集</button><button class="btn danger sm" data-rddel="${esc(k)}">削除</button></div></div>`).join('') : `<p class="muted">読み仮名の登録はありません。入力時に自動記録されるほか、ここで手動追加できます。</p>`;
    $$('[data-rdedit]', host).forEach(b => b.addEventListener('click', () => openReadingModal(b.dataset.rdedit)));
    $$('[data-rddel]', host).forEach(b => b.addEventListener('click', () => { delete state.readings[b.dataset.rddel]; persist(); renderReadings(); toast('削除しました'); }));
  }
  function openReadingModal(key) {
    const editing = key != null && state.readings[key] != null; const k0 = editing ? key : ''; const v0 = editing ? state.readings[key] : '';
    $('#modal').innerHTML = `<h3>${editing ? '読み仮名を編集' : '読み仮名を追加'}</h3><div class="field"><label>表示名（店名・品目など）</label><input id="rd_key" value="${esc(k0)}" placeholder="例: 紀伊國屋書店"></div><div class="field"><label>よみ（ひらがな）</label><input id="rd_yomi" value="${esc(v0)}" placeholder="例: きのくにやしょてん"></div><p class="hint">登録すると、その表示名を「よみ」でも検索できます。</p><div class="actions"><button class="btn ghost" id="rd_cancel">キャンセル</button><button class="btn" id="rd_ok">保存</button></div>`;
    $('#rd_cancel').addEventListener('click', closeModal);
    $('#rd_ok').addEventListener('click', () => { const k = $('#rd_key').value.trim(); const v = $('#rd_yomi').value.trim(); if (!k || !v) return toast('表示名とよみを入力してください'); if (editing && k !== key) delete state.readings[key]; state.readings[k] = v; persist(); closeModal(); renderReadings(); toast('保存しました ✓'); });
    showModal();
  }

  function renderTplBar() {
    const bar = $('#tplBar'); if (!bar) return;
    if (!state.templates.length) bar.innerHTML = `<span class="lbl">テンプレなし（設定で追加）</span> <button class="tpl-chip" id="tplSaveCur">＋現在の入力を保存</button>`;
    else bar.innerHTML = `<span class="lbl">テンプレ:</span>` + state.templates.map(t => `<button class="tpl-chip" data-tpl="${t.id}">${esc(t.name)}</button>`).join('') + ` <button class="tpl-chip" id="tplSaveCur" style="border-color:var(--accent);color:var(--accent)">＋現在を保存</button>`;
    $$('#tplBar [data-tpl]').forEach(b => b.addEventListener('click', () => loadTemplate(b.dataset.tpl)));
    const sc = $('#tplSaveCur'); if (sc) sc.addEventListener('click', saveCurrentAsTemplate);
  }
  function loadTemplate(id) { const t = state.templates.find(x => x.id === id); if (!t) return; ui._store = t.store || ''; ui._branch = t.branch || ''; ui.exp.debits = (t.items && t.items.length) ? t.items.map(it => ({ path: it.catPath, amt: it.amount ? String(it.amount) : '', ratio: '' })) : [{ path: '', amt: '', ratio: '' }]; ui.exp.credits = [{ accId: t.creditAccId || '', amt: '' }]; ui.exp.detail = false; ui.exp.total = ''; renderEntry(); const first = $('#debitArea .d_amt'); if (first) first.focus(); toast(`テンプレ「${t.name}」を読み込みました。金額を入力してください`); }
  function saveCurrentAsTemplate() { syncExpFromDOM(); const items = ui.exp.debits.filter(d => d.path).map(d => ({ catPath: d.path, amount: 0 })); if (!items.length) return toast('明細のカテゴリを1つ以上入れてください'); const name = prompt('テンプレ名を入力', ui._store || 'テンプレ'); if (!name) return; const creditAccId = (ui.exp.credits[0] && ui.exp.credits[0].accId) || (accountsBy(a => a.subtype === 'cash')[0] || {}).id || ''; state.templates.push({ id: 'tpl_' + Math.random().toString(36).slice(2, 8), name: name.trim(), store: ui._store || '', branch: ui._branch || '', creditAccId, padMode: 'calc', items }); persist(); renderTplBar(); toast('テンプレを保存しました ✓'); }
  function renderTplList() { const host = $('#tplList'); if (!host) return; host.innerHTML = state.templates.length ? state.templates.map(t => `<div class="rec-row"><div class="rn"><div class="acc-name">${esc(t.name)} <span class="tag">${t.padMode === 'receipt' ? 'レシート' : '電卓'}</span></div><div class="acc-sub">${t.store ? esc(t.store) + (t.branch ? ' / ' + esc(t.branch) : '') + ' ・ ' : ''}${t.items.map(it => it.catPath.replace(/^exp>/, '').split('>').slice(-1)[0]).join('・')} ・ ${accName(t.creditAccId)}</div></div><div class="row" style="gap:6px"><button class="btn ghost sm" data-tpledit="${t.id}">編集</button><button class="btn danger sm" data-tpldel="${t.id}">削除</button></div></div>`).join('') : `<p class="muted">テンプレがありません。入力画面で組み立てて「現在を保存」も便利です。</p>`; $$('[data-tpledit]', host).forEach(b => b.addEventListener('click', () => openTplModal(b.dataset.tpledit))); $$('[data-tpldel]', host).forEach(b => b.addEventListener('click', () => { if (!confirm('テンプレを削除しますか？')) return; state.templates = state.templates.filter(t => t.id !== b.dataset.tpldel); persist(); renderTplList(); toast('削除しました'); })); }
  function openTplModal(id) {
    const editing = id ? state.templates.find(t => t.id === id) : null; const t = editing || { id: 'tpl_' + Math.random().toString(36).slice(2, 8), name: '', store: '', branch: '', creditAccId: (accountsBy(a => a.subtype === 'cash')[0] || {}).id || '', padMode: 'calc', items: [{ catPath: 'exp>食費>食材>主食', amount: 0 }] }; let items = t.items.map(it => ({ ...it }));
    const draw = () => { $('#modal').innerHTML = `<h3>${editing ? 'テンプレを編集' : 'テンプレを追加'}</h3><div class="field"><label>テンプレ名</label><input id="tp_name" value="${esc(t.name)}" placeholder="例: いつものスーパー"></div><div class="row"><div class="field" style="flex:2"><label>店名(任意)</label><input id="tp_store" value="${esc(t.store)}"></div><div class="field"><label>支店(任意)</label><input id="tp_branch" value="${esc(t.branch)}"></div></div><div class="row"><div class="field"><label>支払手段</label><select id="tp_acc">${accountOptions(a => a.subtype !== 'voucher_goods', t.creditAccId)}</select></div><div class="field"><label>入力方式</label><select id="tp_pad"><option value="calc" ${t.padMode !== 'receipt' ? 'selected' : ''}>電卓</option><option value="receipt" ${t.padMode === 'receipt' ? 'selected' : ''}>レシート</option></select></div></div><label>明細カテゴリ（金額は呼び出し後に入力）</label><div id="tp_items">${items.map((it, i) => `<div class="line-row" data-i="${i}"><div class="field cat"><select class="tp_cat catsel">${categoryOptions('expense', it.catPath)}</select></div><div><button class="btn ghost sm tp_del">✕</button></div></div>`).join('')}</div><button class="btn ghost sm" id="tp_add">＋明細を追加</button><div class="actions"><button class="btn ghost" id="tp_cancel">キャンセル</button><button class="btn" id="tp_save">保存</button></div>`;
      $$('#tp_items .line-row').forEach(row => { const i = +row.dataset.i; row.querySelector('.tp_cat').addEventListener('change', e => items[i].catPath = e.target.value); row.querySelector('.tp_del').addEventListener('click', () => { syncTp(); items.splice(i, 1); if (!items.length) items.push({ catPath: 'exp>食費>食材>主食', amount: 0 }); draw(); }); });
      $('#tp_add').addEventListener('click', () => { syncTp(); items.push({ catPath: 'exp>食費>食材>主食', amount: 0 }); draw(); }); $('#tp_cancel').addEventListener('click', closeModal); decorateInputs($('#modal'));
      $('#tp_save').addEventListener('click', () => { syncTp(); const name = $('#tp_name').value.trim(); if (!name) return toast('テンプレ名を入れてください'); t.name = name; t.store = $('#tp_store').value; t.branch = $('#tp_branch').value; t.creditAccId = $('#tp_acc').value; t.padMode = $('#tp_pad').value; t.items = items.map(it => ({ catPath: it.catPath, amount: 0 })); if (!editing) state.templates.push(t); persist(); closeModal(); renderTplList(); renderTplBar(); toast('保存しました ✓'); });
      function syncTp() { $$('#tp_items .line-row').forEach(row => { const i = +row.dataset.i; items[i].catPath = row.querySelector('.tp_cat').value; }); }
    };
    draw(); showModal();
  }

  

