  /* ============ 予算・積立 ============ */
  function renderBudget() {
    if ($('#tab-budget').hidden) return; const ym = currentYM(); const rep = M.budgetReport(state, ym); const overRatio = rep.totalBudget > 0 ? rep.totalSpent / rep.totalBudget : 0;
    if ($('#budRollover')) $('#budRollover').checked = !!state.budgetRollover;
    $('#budgetCards').innerHTML = [['予算合計', yen(rep.totalBudget), ''], ['支出合計', yen(rep.totalSpent), rep.totalSpent > rep.totalBudget ? 'neg' : ''], ['残り', yen(rep.totalRemain), rep.totalRemain < 0 ? 'neg' : 'pos']].map(([k, v, c]) => `<div class="stat"><div class="k">${k}（${ym}）</div><div class="v ${c}">${v}</div><div class="sub">${k === '支出合計' ? Math.round(overRatio * 100) + '% 消化' : (k === '予算合計' && rep.rollover ? '繰越込み' : '')}</div></div>`).join('');
    $('#budgetList').innerHTML = rep.entries.length ? rep.entries.map(e => { const p = Math.round(e.ratio * 100); const cls = e.ratio >= 1 ? 'over' : (e.ratio >= 0.8 ? 'warn' : ''); const carryHtml = (rep.rollover && Math.abs(e.carry) > 0.5) ? ` <span class="acc-sub">(基準 ${yen(e.budget)} ${e.carry >= 0 ? '＋繰越 ' : '−超過 '}${yen(Math.abs(e.carry))})</span>` : ''; return `<div class="bud-row"><div class="bud-head"><div><span class="bud-name">${esc(e.label)}</span> <span class="acc-sub">${p}% 消化</span>${carryHtml}</div><div class="bud-fig">${yen(e.spent)} / ${yen(e.effective)} ・ 残 <b class="${e.remain < 0 ? 'neg' : 'pos'}">${yen(e.remain)}</b> <button class="btn ghost sm" data-budedit="${esc(e.catPath)}">編集</button> <button class="btn danger sm" data-buddel="${esc(e.catPath)}">削除</button></div></div><div class="bar ${cls}"><span style="width:${Math.min(100, p)}%"></span></div></div>`; }).join('') : `<p class="muted">予算が未設定です。「＋予算」から追加してください。</p>`;
    $$('[data-budedit]', $('#budgetList')).forEach(b => b.addEventListener('click', () => openBudgetModal(b.dataset.budedit)));
    $$('[data-buddel]', $('#budgetList')).forEach(b => b.addEventListener('click', () => { delete state.budgets[b.dataset.buddel]; persist(); renderBudget(); renderDrill(); toast('予算を削除しました'); }));
  }
  function openBudgetModal(catPath) { const editing = catPath != null; const cur = editing ? state.budgets[catPath] : 0; const opts = M.budgetableCategories(state.categories).map(c => `<option value="${c.path}" ${c.path === catPath ? 'selected' : ''}>${c.label}</option>`).join(''); $('#modal').innerHTML = `<h3>${editing ? '予算を編集' : '予算を設定'}</h3><div class="field"><label>カテゴリ（大/中/小どの階層でもOK）</label><select id="bud_cat" class="catsel" ${editing ? 'disabled' : ''}>${opts}</select></div><div class="field"><label>月予算</label><input type="number" id="bud_amt" value="${cur || ''}" placeholder="例: 40000"></div><p class="hint">この階層＋配下すべての支出を合計。分析画面にも表示されます。</p><div class="actions"><button class="btn ghost" id="bud_cancel">キャンセル</button><button class="btn" id="bud_ok">保存</button></div>`; $('#bud_cancel').addEventListener('click', closeModal); $('#bud_ok').addEventListener('click', () => { const path = editing ? catPath : $('#bud_cat').value; const amt = +$('#bud_amt').value; if (!amt) return toast('金額を入れてください'); state.budgets[path] = amt; persist(); closeModal(); renderBudget(); renderDrill(); toast('保存しました ✓'); }); showModal(); }

  function effectiveSurplus() { return (simSurplus != null) ? simSurplus : M.avgMonthlySurplus(state, currentYM(), 3); }
  function renderGoals() {
    const ym = currentYM(); const surplus = effectiveSurplus(); const avg = M.avgMonthlySurplus(state, ym, 3);
    if ($('#simSurplus') && document.activeElement !== $('#simSurplus')) $('#simSurplus').value = surplus;
    if ($('#simHint')) $('#simHint').textContent = `直近3か月の平均余剰（収入−支出）は ${yen(avg)}。ここを積立に回せる額の目安に。`;
    renderGoalTimeline(surplus);
    const sim = M.simulateGoals(state, ym, surplus); const simById = {}; sim.forEach(g => simById[g.id] = g);
    const goals = state.goals.slice().sort((a, b) => (a.priority - b.priority) || String(a.targetYM || '9999').localeCompare(String(b.targetYM || '9999')));
    $('#goalList').innerHTML = goals.length ? goals.map(g => { const remain = Math.max(0, (g.target || 0) - (g.saved || 0)); const p = M.pct(g.saved || 0, g.target || 1); const req = M.goalRequiredMonthly(g, ym); const s = simById[g.id]; const proj = s ? s.doneYM : null; let status = 'none', statusText = '期限なし'; if (g.targetYM) { if (remain <= 0) { status = 'ok'; statusText = '達成済み'; } else if (proj && proj <= g.targetYM) { status = 'ok'; statusText = '間に合う見込み'; } else { status = 'behind'; statusText = '遅れる見込み'; } } else if (remain <= 0) { status = 'ok'; statusText = '達成済み'; } const cls = p >= 100 ? '' : (p >= 80 ? 'warn' : ''); return `<div class="goal-card"><div class="goal-top"><div><div class="goal-name">${esc(g.name)}</div><div class="goal-meta">優先度 ${g.priority || 3}${g.targetYM ? ' ・ 目標 ' + g.targetYM : ' ・ 期限なし'}${g.linkedAccId ? ' ・ 紐付 ' + accName(g.linkedAccId) : ''}${g.note ? ' ・ ' + esc(g.note) : ''}</div></div><span class="goal-status ${status}">${statusText}</span></div><div class="bar ${cls}" style="margin:10px 0"><span style="width:${Math.min(100, p)}%"></span></div><div class="goal-figs"><div><div class="fk">積立済 / 目標</div><div class="fv">${yen(g.saved || 0)} / ${yen(g.target || 0)}（${p}%）</div></div><div><div class="fk">残り</div><div class="fv">${yen(remain)}</div></div>${g.targetYM ? `<div><div class="fk">必要月額</div><div class="fv">${req == null ? '—' : yen(req)}</div></div>` : ''}<div><div class="fk">この配分での達成</div><div class="fv">${remain <= 0 ? '完了' : (proj || '20年以上')}</div></div></div><div class="row" style="gap:6px"><button class="btn ghost sm" data-goalsave="${g.id}">積立を記録</button><button class="btn ghost sm" data-goaledit="${g.id}">編集</button><button class="btn danger sm" data-goaldel="${g.id}">削除</button></div></div>`; }).join('') : `<p class="muted">目標がありません。「＋目標」から作成してください。</p>`;
    $$('[data-goaledit]', $('#goalList')).forEach(b => b.addEventListener('click', () => openGoalModal(b.dataset.goaledit)));
    $$('[data-goaldel]', $('#goalList')).forEach(b => b.addEventListener('click', () => { if (!confirm('目標を削除しますか？')) return; state.goals = state.goals.filter(g => g.id !== b.dataset.goaldel); state.wishlist.forEach(w => { if (w.goalId === b.dataset.goaldel) w.goalId = null; }); persist(); renderGoals(); renderWishlist(); toast('削除しました'); }));
    $$('[data-goalsave]', $('#goalList')).forEach(b => b.addEventListener('click', () => openGoalSaveModal(b.dataset.goalsave)));
  }
  function renderGoalTimeline(surplus) {
    const host = $('#goalTimeline'); if (!host) return; const ym = currentYM(); const tl = M.goalTimeline(state, ym, surplus); if (!tl.rows.length) { host.innerHTML = ''; return; }
    const span = Math.max(1, tl.maxIdx - tl.startIdx); const startIdx = tl.startIdx; const axisMonths = tl.months.filter((m, i) => i % Math.ceil(tl.months.length / 8) === 0);
    const rows = tl.rows.map((r, i) => { const col = PALETTE[i % PALETTE.length]; const doneIdx = r.doneYM ? M.ymIndex(r.doneYM) : tl.maxIdx; const widthPct = Math.min(100, (doneIdx - startIdx) / span * 100); const savedW = widthPct * r.savedRatio; const tgt = r.targetYM ? Math.min(100, (M.ymIndex(r.targetYM) - startIdx) / span * 100) : null; const doneLbl = r.doneYM ? (r.doneYM === ym ? '完了' : r.doneYM) : '20年+'; return `<div class="gantt-row"><div class="gantt-label" title="${esc(r.name)}">${esc(r.name)}</div><div class="gantt-track"><div class="gantt-bar" style="left:0%; width:${widthPct}%; background:${col}; opacity:.35"></div><div class="gantt-bar" style="left:0%; width:${savedW}%; background:${col}"></div>${tgt != null ? `<div class="gantt-target" style="left:${tgt}%" title="目標 ${r.targetYM}"></div>` : ''}<div class="gantt-done" style="left:${Math.min(92, widthPct)}%">${doneLbl}</div></div></div>`; }).join('');
    host.innerHTML = `<div class="gantt"><div class="acc-sub" style="margin-bottom:6px">達成タイムライン（塗り=積立済 / 薄い=このペースでの到達 / 縦線=目標月）</div>${rows}<div class="gantt-axis">${axisMonths.map(m => `<span>${m.slice(2)}</span>`).join('')}</div></div>`;
  }
  function openGoalSaveModal(id) { const g = state.goals.find(x => x.id === id); if (!g) return; const remain = Math.max(0, (g.target || 0) - (g.saved || 0)); $('#modal').innerHTML = `<h3>積立を記録：${esc(g.name)}</h3><p class="hint">仮想封筒への取り分けを記録します（帳簿の仕訳は作りません）。</p><div class="field"><label>今回積み立てる額（残り ${yen(remain)}）</label><input type="number" id="gs_amt" placeholder="例: 20000"></div><div class="field"><label><input type="checkbox" id="gs_xfer" style="width:auto" ${g.linkedAccId ? '' : 'disabled'}> 同時に振替も記帳する${g.linkedAccId ? '（→ ' + accName(g.linkedAccId) + '）' : '（紐付口座なし）'}</label></div><div id="gs_xferFields" style="display:none"><div class="field"><label>振替元口座</label><select id="gs_from">${accountOptions(a => ['bank', 'cash'].includes(a.subtype))}</select></div></div><div class="actions"><button class="btn ghost" id="gs_cancel">キャンセル</button><button class="btn" id="gs_ok">記録</button></div>`; $('#gs_xfer').addEventListener('change', e => $('#gs_xferFields').style.display = e.target.checked ? '' : 'none'); $('#gs_cancel').addEventListener('click', closeModal); $('#gs_ok').addEventListener('click', () => { const amt = +$('#gs_amt').value; if (!amt) return toast('金額を入れてください'); g.saved = (g.saved || 0) + amt; if ($('#gs_xfer').checked && g.linkedAccId) { const from = $('#gs_from').value; if (from && from !== g.linkedAccId) state.transactions.push(M.buildTransfer({ date: M.todayStr(), fromAccId: from, toAccId: g.linkedAccId, amount: amt, store: '積立', memo: '積立: ' + g.name })); } persist(); closeModal(); renderGoals(); renderAccounts(); renderList(); toast('積立を記録しました ✓'); }); showModal(); }
  function openGoalModal(id) { const editing = id ? state.goals.find(g => g.id === id) : null; const g = editing || { id: 'g_' + Math.random().toString(36).slice(2, 8), name: '', target: 0, targetYM: '', saved: 0, priority: 3, note: '', linkedAccId: null }; $('#modal').innerHTML = `<h3>${editing ? '目標を編集' : '目標を追加'}</h3><div class="field"><label>目標名</label><input id="go_name" value="${esc(g.name)}" placeholder="例: Mac買い替え / 旅行 / 予備資金"></div><div class="row"><div class="field"><label>目標額</label><input type="number" id="go_target" value="${g.target || ''}"></div><div class="field"><label>現在の積立済</label><input type="number" id="go_saved" value="${g.saved || 0}"></div></div><div class="row"><div class="field"><label>目標月（任意）</label><input type="month" id="go_ym" value="${g.targetYM || ''}"></div><div class="field"><label>優先度(1=最優先)</label><input type="number" id="go_pri" min="1" max="9" value="${g.priority || 3}"></div></div><div class="field"><label>紐付ける積立口座（任意）</label><select id="go_acc"><option value="">なし（仮想のみ）</option>${accountOptions(a => M.ACCOUNT_SUBTYPES[a.subtype].kind === 'asset', g.linkedAccId)}</select></div><div class="field"><label>メモ</label><input id="go_note" value="${esc(g.note || '')}"></div><div class="actions"><button class="btn ghost" id="go_cancel">キャンセル</button><button class="btn" id="go_ok">保存</button></div>`; $('#go_cancel').addEventListener('click', closeModal); $('#go_ok').addEventListener('click', () => { const name = $('#go_name').value.trim(); if (!name) return toast('目標名を入れてください'); const target = +$('#go_target').value; if (!target) return toast('目標額を入れてください'); const obj = editing || g; obj.name = name; obj.target = target; obj.saved = +$('#go_saved').value || 0; obj.targetYM = $('#go_ym').value || null; obj.priority = +$('#go_pri').value || 3; obj.linkedAccId = $('#go_acc').value || null; obj.note = $('#go_note').value; if (!editing) state.goals.push(obj); persist(); closeModal(); renderGoals(); toast('保存しました ✓'); }); showModal(); }

