  /* ============ ほしいもの ============ */
  function allWishTags() { const s = new Set(); state.wishlist.forEach(w => (w.tags || []).forEach(t => s.add(t))); return [...s].sort((a, b) => a.localeCompare(b, 'ja')); }
  function renderWishlist() {
    if ($('#tab-wishlist').hidden) return; const tags = allWishTags();
    $('#wishTags').innerHTML = `<span class="muted" style="font-size:12px">表示:</span>` + `<button class="chip-btn ${wishFilter.status === 'active' ? 'active' : ''}" data-st="active">未購入</button>` + `<button class="chip-btn ${wishFilter.status === 'done' ? 'active' : ''}" data-st="done">購入済</button>` + `<button class="chip-btn ${wishFilter.status === 'all' ? 'active' : ''}" data-st="all">すべて</button>` + `<span style="width:8px"></span><span class="muted" style="font-size:12px">タグ:</span>` + `<button class="chip-btn ${wishFilter.tag == null ? 'active' : ''}" data-tag="">全部</button>` + tags.map(t => `<button class="chip-btn ${wishFilter.tag === t ? 'active' : ''}" data-tag="${esc(t)}">${esc(t)}</button>`).join('');
    $$('#wishTags [data-st]').forEach(b => b.addEventListener('click', () => { wishFilter.status = b.dataset.st; renderWishlist(); }));
    $$('#wishTags [data-tag]').forEach(b => b.addEventListener('click', () => { wishFilter.tag = b.dataset.tag || null; renderWishlist(); }));
    let list = state.wishlist.slice(); if (wishFilter.status !== 'all') list = list.filter(w => (w.status || 'active') === wishFilter.status); if (wishFilter.tag) list = list.filter(w => (w.tags || []).includes(wishFilter.tag)); list.sort((a, b) => (a.priority - b.priority) || String(a.desiredYM || '9999').localeCompare(String(b.desiredYM || '9999')));
    const activeAll = state.wishlist.filter(w => (w.status || 'active') === 'active'); const total = activeAll.reduce((s, w) => s + (w.price || 0), 0); const byYM = {}; activeAll.forEach(w => { const k = w.desiredYM || '時期未定'; byYM[k] = (byYM[k] || 0) + (w.price || 0); });
    $('#wishSummary').innerHTML = `未購入 合計 ${yen(total)} ・ ` + Object.entries(byYM).sort().map(([k, v]) => `${k}: ${yen(v)}`).join(' / ');
    $('#wishList').innerHTML = list.length ? list.map(w => { const done = (w.status || 'active') === 'done'; const tagHtml = (w.tags || []).map(t => `<span class="tag">${esc(t)}</span>`).join(' '); return `<div class="wish-row ${done ? 'done' : ''}"><span class="wish-name">${esc(w.name)}<span class="wish-tags">${tagHtml}</span> <span class="acc-sub">優先${w.priority || 3}${w.desiredYM ? ' ・ ' + w.desiredYM + 'ごろ' : ''}${w.store ? ' ・ ' + esc(w.store) : ''}${w.note ? ' ・ ' + esc(w.note) : ''}${w.goalId ? ' ・ <span class="tag best">積立中</span>' : ''}</span></span><span class="wish-price">${yen(w.price || 0)}</span><div class="row" style="gap:6px"><button class="btn ghost sm" data-wishlink="${esc(w.name)}">🔗支出</button><button class="btn ghost sm" data-wishdone="${w.id}">${done ? '未購入に' : '購入済に'}</button>${w.goalId || done ? '' : `<button class="btn ghost sm" data-wishgoal="${w.id}">積立目標に</button>`}<button class="btn ghost sm" data-wishedit="${w.id}">編集</button><button class="btn danger sm" data-wishdel="${w.id}">削除</button></div></div>`; }).join('') : `<p class="muted">該当するほしいものがありません。</p>`;
    $$('[data-wishedit]', $('#wishList')).forEach(b => b.addEventListener('click', () => openWishModal(b.dataset.wishedit)));
    $$('[data-wishdel]', $('#wishList')).forEach(b => b.addEventListener('click', () => { if (!confirm('削除しますか？')) return; state.wishlist = state.wishlist.filter(w => w.id !== b.dataset.wishdel); persist(); renderWishlist(); toast('削除しました'); }));
    $$('[data-wishdone]', $('#wishList')).forEach(b => b.addEventListener('click', () => { const w = state.wishlist.find(x => x.id === b.dataset.wishdone); if (!w) return; w.status = (w.status === 'done') ? 'active' : 'done'; persist(); renderWishlist(); toast(w.status === 'done' ? '購入済にしました' : '未購入に戻しました'); }));
    $$('[data-wishlink]', $('#wishList')).forEach(b => b.addEventListener('click', () => gotoListWithKeyword(b.dataset.wishlink)));
    $$('[data-wishgoal]', $('#wishList')).forEach(b => b.addEventListener('click', () => { const w = state.wishlist.find(x => x.id === b.dataset.wishgoal); if (!w) return; const goal = { id: 'g_' + Math.random().toString(36).slice(2, 8), name: w.name, target: w.price || 0, targetYM: w.desiredYM || null, saved: 0, priority: w.priority || 3, note: w.note || 'ほしいものから', linkedAccId: null }; state.goals.push(goal); w.goalId = goal.id; persist(); renderWishlist(); toast('積立目標に変換しました ✓（予算・積立タブで確認）'); }));
  }
  function openWishModal(id) { const editing = id ? state.wishlist.find(w => w.id === id) : null; const w = editing || { id: 'w_' + Math.random().toString(36).slice(2, 8), name: '', price: 0, desiredYM: '', priority: 3, note: '', goalId: null, tags: [], status: 'active', store: '', url: '' }; const tagSug = allWishTags(); $('#modal').innerHTML = `<h3>${editing ? 'ほしいものを編集' : 'ほしいものを追加'}</h3><div class="field"><label>名称</label><input id="wi_name" value="${esc(w.name)}" placeholder="例: ヘッドホン / 包丁 / クミンパウダー"></div><div class="row"><div class="field"><label>価格(目安)</label><input type="number" id="wi_price" value="${w.price || ''}"></div><div class="field"><label>ほしい時期(任意)</label><input type="month" id="wi_ym" value="${w.desiredYM || ''}"></div><div class="field"><label>優先度(1=高)</label><input type="number" id="wi_pri" min="1" max="9" value="${w.priority || 3}"></div></div><div class="row"><div class="field"><label>買う店(任意)</label><input id="wi_store" list="dl-store" value="${esc(w.store || '')}" placeholder="例: ニトリ / Amazon"></div><div class="field"><label>URL(任意)</label><input id="wi_url" value="${esc(w.url || '')}" placeholder="https://"></div></div><div class="field"><label>タグ（カンマ区切り）</label><input id="wi_tags" value="${esc((w.tags || []).join(', '))}" placeholder="例: ネットで買う, キッチン"></div>${tagSug.length ? `<div class="chips" id="wi_tagsug">${tagSug.map(t => `<button type="button" class="chip-btn" data-t="${esc(t)}">+ ${esc(t)}</button>`).join('')}</div>` : ''}<div class="field"><label>メモ</label><input id="wi_note" value="${esc(w.note || '')}"></div><div class="actions"><button class="btn ghost" id="wi_cancel">キャンセル</button><button class="btn" id="wi_ok">保存</button></div>`; $$('#wi_tagsug .chip-btn').forEach(b => b.addEventListener('click', () => { const cur = $('#wi_tags').value.split(',').map(s => s.trim()).filter(Boolean); if (!cur.includes(b.dataset.t)) cur.push(b.dataset.t); $('#wi_tags').value = cur.join(', '); })); $('#wi_cancel').addEventListener('click', closeModal); $('#wi_ok').addEventListener('click', () => { const name = $('#wi_name').value.trim(); if (!name) return toast('名称を入れてください'); const obj = editing || w; obj.name = name; obj.price = +$('#wi_price').value || 0; obj.desiredYM = $('#wi_ym').value || null; obj.priority = +$('#wi_pri').value || 3; obj.store = $('#wi_store').value; obj.url = $('#wi_url').value; obj.tags = $('#wi_tags').value.split(',').map(s => s.trim()).filter(Boolean); obj.note = $('#wi_note').value; if (!editing) { obj.status = 'active'; state.wishlist.push(obj); } persist(); closeModal(); renderWishlist(); toast('保存しました ✓'); }); showModal(); }

  /* ============ 価格比較 ============ */
  const PRICE_UNITS = ['総額', 'g', 'kg', 'ml', 'L', '個', '本', '枚', '杯'];
  const PRICE_PREVIEW = 3;
  function renderPrice() {
    if ($('#tab-price').hidden) return; const items = M.priceItems(state);
    $('#priceList').innerHTML = items.length ? items.map(it => {
      const open = priceOpen.has(it.item); const showAll = priceShowAll.has(it.item);
      const best = it.entries.find(e => e.id === it.bestId);
      const shown = showAll ? it.entries : it.entries.slice(0, PRICE_PREVIEW);
      const rowsHtml = shown.map(e => `<tr class="${e.id === it.bestId ? 'best' : ''}"><td>${e.date}</td><td>${esc(e.store)}${e.branch ? ' <span class="muted">/ ' + esc(e.branch) + '</span>' : ''}</td><td class="num">${yen(e.price)}</td><td class="num">${e.qty}${esc(e.unit)}</td><td class="num">${e.norm ? fmtNorm(e.norm) : '—'} ${e.id === it.bestId ? '<span class="tag best">最安</span>' : ''}</td><td class="muted">${esc(e.note)}</td><td style="white-space:nowrap"><button class="btn ghost sm" data-pledit="${e.id}">編集</button> <button class="btn danger sm" data-pldel="${e.id}">削除</button></td></tr>`).join('');
      const moreBtn = it.entries.length > PRICE_PREVIEW ? `<div class="pl-more"><button class="btn ghost sm" data-plmore="${esc(it.item)}">${showAll ? '直近' + PRICE_PREVIEW + '件に折りたたむ' : '全 ' + it.entries.length + '件を表示'}</button></div>` : '';
      const chart = it.count >= 2 ? drawPriceChart(it.item, priceRange[it.item] || '6') : '';
      return `<div class="pl-item ${open ? 'open' : ''}"><div class="pl-item-head" data-pltoggle="${esc(it.item)}"><span class="pl-item-name"><span class="pl-caret">▶</span> ${esc(it.item)} <span class="acc-sub">${it.count}件・最新 ${it.lastDate}</span></span><span style="display:flex;gap:10px;align-items:center"><span class="pl-best">${best && best.norm ? '最安 ' + esc(best.store) + ' ・ ' + fmtNorm(best.norm) : ''}</span><button class="btn ghost sm" data-pllink="${esc(it.item)}">🔗支出</button></span></div><div class="pl-body"><div style="overflow:auto"><table><thead><tr><th>日付</th><th>店</th><th class="num">価格</th><th class="num">数量</th><th class="num">実質単価</th><th>メモ</th><th></th></tr></thead><tbody>${rowsHtml}</tbody></table></div>${moreBtn}${chart}</div></div>`;
    }).join('') : `<p class="muted">価格の記録がありません。「＋価格を記録」から追加してください。</p>`;
    $$('#priceList [data-pltoggle]').forEach(h => h.addEventListener('click', e => { if (e.target.closest('[data-pllink]')) return; const it = h.dataset.pltoggle; if (priceOpen.has(it)) priceOpen.delete(it); else priceOpen.add(it); renderPrice(); }));
    $$('#priceList [data-plmore]').forEach(b => b.addEventListener('click', e => { e.stopPropagation(); const it = b.dataset.plmore; if (priceShowAll.has(it)) priceShowAll.delete(it); else priceShowAll.add(it); renderPrice(); }));
    $$('#priceList [data-pllink]').forEach(b => b.addEventListener('click', e => { e.stopPropagation(); gotoListWithKeyword(b.dataset.pllink); }));
    $$('#priceList [data-plrange]').forEach(b => b.addEventListener('click', e => { e.stopPropagation(); const [it, rg] = b.dataset.plrange.split('|'); priceRange[it] = rg; renderPrice(); }));
    $$('#priceList [data-pledit]').forEach(b => b.addEventListener('click', e => { e.stopPropagation(); openPriceModal(b.dataset.pledit); }));
    $$('#priceList [data-pldel]').forEach(b => b.addEventListener('click', e => { e.stopPropagation(); if (!confirm('削除しますか？')) return; state.priceLogs = state.priceLogs.filter(p => p.id !== b.dataset.pldel); persist(); renderPrice(); toast('削除しました'); }));
  }
  function drawPriceChart(item, range) {
    const ser = M.priceSeries(state, item, 3); let pts = ser.points; if (pts.length < 2) return '';
    const full = pts.length; if (range === '6' && pts.length > 6) pts = pts.slice(-6);
    const W = 560, H = 150, padL = 44, padR = 10, padT = 12, padB = 22; const vals = pts.map(p => p.value).concat(pts.map(p => p.ma)); const min = Math.min(...vals), max = Math.max(...vals); const rng = (max - min) || 1; const iw = W - padL - padR, ih = H - padT - padB;
    const x = i => padL + (pts.length === 1 ? iw / 2 : i / (pts.length - 1) * iw); const y = v => padT + (1 - (v - min) / rng) * ih;
    const linePath = pts.map((p, i) => (i ? 'L' : 'M') + x(i).toFixed(1) + ' ' + y(p.value).toFixed(1)).join(' '); const maPath = pts.map((p, i) => (i ? 'L' : 'M') + x(i).toFixed(1) + ' ' + y(p.ma).toFixed(1)).join(' ');
    let grid = '', dots = '', xax = ''; for (let g = 0; g <= 2; g++) { const vv = min + rng * g / 2; const yy = y(vv); grid += `<line x1="${padL}" y1="${yy}" x2="${W - padR}" y2="${yy}" stroke="var(--line)" stroke-dasharray="3 3"/><text class="pc-ax" x="2" y="${yy + 3}">${Math.round(vv)}</text>`; }
    pts.forEach((p, i) => { dots += `<circle class="pc-dot" cx="${x(i).toFixed(1)}" cy="${y(p.value).toFixed(1)}" r="3"><title>${p.date} ${esc(p.store)} ${Math.round(p.value * 100) / 100} ${ser.label}</title></circle>`; if (i === 0 || i === pts.length - 1 || pts.length <= 6) xax += `<text class="pc-ax" x="${x(i).toFixed(1)}" y="${H - 6}" text-anchor="middle">${p.date.slice(5)}</text>`; });
    const rangeBtns = full > 6 ? `<span class="pc-range"><button class="${range === '6' ? 'active' : ''}" data-plrange="${esc(item)}|6">直近6</button><button class="${range === 'all' ? 'active' : ''}" data-plrange="${esc(item)}|all">全期間</button></span>` : '';
    return `<div class="pl-chart"><svg viewBox="0 0 ${W} ${H}">${grid}<path class="pc-ma" d="${maPath}"/><path class="pc-line" d="${linePath}"/>${dots}${xax}</svg><div class="pc-legend"><span><span class="pc-sw" style="background:var(--accent)"></span>実質単価 (${esc(ser.label)})</span><span><span class="pc-sw" style="background:var(--warn)"></span>移動平均(3)</span>${rangeBtns}</div></div>`;
  }
  function fmtNorm(n) { return (Math.round(n.value * 100) / 100).toLocaleString('ja-JP') + ' ' + n.label; }
  function openPriceModal(id) { const editing = id ? state.priceLogs.find(p => p.id === id) : null; const e = editing || { id: 'pl_' + Math.random().toString(36).slice(2, 8), item: '', date: M.todayStr(), store: '', branch: '', price: 0, qty: 0, unit: '総額', note: '' }; $('#modal').innerHTML = `<h3>${editing ? '価格を編集' : '価格を記録'}</h3><div class="field"><label>品目</label><input id="pl_item" list="dl-item" value="${esc(e.item)}" placeholder="例: 卵(10個) / 牛乳 / 鶏むね肉"></div><div class="row"><div class="field"><label>日付</label><input type="date" id="pl_date" value="${e.date}"></div><div class="field" style="flex:2"><label>店名</label><input id="pl_store" list="dl-store" value="${esc(e.store)}"></div><div class="field"><label>支店</label><input id="pl_branch" list="dl-branch" value="${esc(e.branch)}"></div></div><div class="row"><div class="field"><label>価格</label><input type="number" id="pl_price" value="${e.price || ''}"></div><div class="field"><label>数量</label><input type="number" id="pl_qty" value="${e.qty || ''}"></div><div class="field"><label>単位</label><select id="pl_unit">${PRICE_UNITS.map(u => `<option ${u === e.unit ? 'selected' : ''}>${u}</option>`).join('')}</select></div></div><div class="acc-sub" id="pl_preview" style="margin-bottom:8px"></div><div class="field"><label>メモ</label><input id="pl_note" value="${esc(e.note || '')}"></div><div class="actions"><button class="btn ghost" id="pl_cancel">キャンセル</button><button class="btn" id="pl_ok">保存</button></div>`; const upd = () => { const n = M.normalizedUnitPrice({ price: +$('#pl_price').value, qty: +$('#pl_qty').value, unit: $('#pl_unit').value }); $('#pl_preview').textContent = n ? '実質単価 ≈ ' + fmtNorm(n) : '数量を入れると実質単価を計算します'; }; ['#pl_price', '#pl_qty', '#pl_unit'].forEach(s => $(s).addEventListener('input', upd)); upd(); $('#pl_cancel').addEventListener('click', closeModal); $('#pl_ok').addEventListener('click', () => { const item = $('#pl_item').value.trim(); if (!item) return toast('品目を入れてください'); const price = +$('#pl_price').value; if (!price) return toast('価格を入れてください'); const data = { item, date: $('#pl_date').value, store: $('#pl_store').value, branch: $('#pl_branch').value, price, qty: +$('#pl_qty').value || 0, unit: $('#pl_unit').value, note: $('#pl_note').value }; if (editing) Object.assign(editing, data); else { M.addPriceLog(state, data); priceOpen.add(item); } persist(); refreshDatalists(); closeModal(); renderPrice(); toast('保存しました ✓'); }); showModal(); }

